from django.urls import path
from . import views

app_name = 'stocks'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('analyze/<str:symbol>/', views.analyze, name='analyze'),
     path('analyze/crew/<str:symbol>/', views.crew_analyze, name='crew_analyze'),
    path('analyze/core/<str:symbol>/', views.core_analyze, name='core_analyze'),
    path('analyze/crew/<str:symbol>/export/docx/', views.crew_export_docx, name='crew_export_docx'),
    path('watchlist/add/', views.add_to_watchlist, name='add_to_watchlist'),
    path('watchlist/<int:pk>/delete/', views.delete_from_watchlist, name='delete_from_watchlist'),
    path('portfolio/', views.portfolio_list, name='portfolio_list'),
    path('portfolio/scan/', views.portfolio_scan, name='portfolio_scan'),
    path('portfolio/add/', views.add_to_portfolio, name='add_to_portfolio'),
    path('portfolio/<int:pk>/delete/', views.delete_from_portfolio, name='delete_from_portfolio'),
    path('portfolio/<int:pk>/sell/', views.sell_stock, name='sell_stock'),
    path('portfolio/report/', views.realized_pl_report, name='realized_pl_report'),
    path('portfolio/tithe/', views.tithe_report, name='tithe_report'),
    path('portfolio/tithe/mark-paid/', views.tithe_mark_paid, name='tithe_mark_paid'),
    path('portfolio/exit-plan/', views.portfolio_exit_plan, name='portfolio_exit_plan'),
    path('recommendations/', views.recommendations, name='recommendations'),
    path('us-recommendations/', views.us_recommendations, name='us_recommendations'),
    path('macro/', views.macro_economy, name='macro'),
    path('momentum/', views.momentum_scanner, name='momentum_scanner'),
    path('momentum/precision/', views.precision_momentum_scanner, name='precision_momentum_scanner'),
    path('momentum/precision/ai/', views.precision_scan_ai_analysis, name='precision_scan_ai_analysis'),
    path('momentum/precision/watchlist/', views.scan_watchlist_view, name='scan_watchlist_view'),
    path('momentum/precision/watchlist/toggle/', views.watchlist_item_toggle, name='watchlist_item_toggle'),
    path('momentum/us-precision/', views.us_precision_scanner, name='us_precision_scanner'),
    path('momentum/us-precision/ai/', views.us_precision_scan_ai_analysis, name='us_precision_scan_ai_analysis'),
    path('momentum/us-sepa/', views.us_sepa_scanner, name='us_sepa_scanner'),
    path('momentum/cup-handle/', views.cup_handle_scanner, name='cup_handle_scanner'),
    path('momentum/us-cup-handle/', views.us_cup_handle_scanner, name='us_cup_handle_scanner'),
    path('momentum/sepa/', views.minervini_sepa_scanner, name='minervini_sepa_scanner'),
    path('momentum/quick-ai/<str:symbol>/', views.momentum_quick_analysis, name='momentum_quick_analysis'),
    path('momentum/us/', views.us_momentum_scanner, name='us_momentum_scanner'),
    path('momentum/us/quick-ai/<str:symbol>/', views.us_momentum_quick_analysis, name='us_momentum_quick_analysis'),
    path('momentum/us/crew/<str:symbol>/', views.us_momentum_crew_page, name='us_momentum_crew_page'),
    path('multi-factor/', views.multi_factor_scanner, name='multi_factor_scanner'),
    path('multi-factor/us/', views.us_multi_factor_scanner, name='us_multi_factor_scanner'),
    path('value/us-value/', views.us_value_scanner, name='us_value_scanner'),
    path('entry-finder/<str:symbol>/', views.entry_finder, name='entry_finder'),
    path('vcp-manual/', views.vcp_manual, name='vcp_manual'),
    path('scanner-guide/', views.scanner_guide, name='scanner_guide'),
    path('scan/turtle/', views.turtle_scanner, name='turtle_scanner'),
    path('scan/turtle/run/', views.turtle_scanner_run_ajax, name='turtle_scanner_run'),
    path('signup/', views.signup, name='signup'),
    path('scan/clear/', views.clear_scan_data, name='clear_scan_data'),
    path('morning-briefing/', views.morning_briefing, name='morning_briefing'),
    path('macro-playbook/', views.macro_playbook_view, name='macro_playbook'),
    path('macro-playbook/run/', views.macro_playbook_run_ajax, name='macro_playbook_run'),
    path('crypto-hub/', views.crypto_hub, name='crypto_hub'),
    path('chart/<str:symbol>/', views.stock_chart, name='stock_chart'),
    path('chart/<str:symbol>/data/', views.stock_chart_data, name='stock_chart_data'),
]

