from django.urls import path
from . import views

app_name = 'stocks'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('analyze/<str:symbol>/', views.analyze, name='analyze'),
     path('analyze/crew/<str:symbol>/', views.crew_analyze, name='crew_analyze'),
    path('analyze/core/<str:symbol>/', views.core_analyze, name='core_analyze'),
    path('analyze/crew/<str:symbol>/export/docx/', views.crew_export_docx, name='crew_export_docx'),
    path('watchlist/add/', views.add_to_watchlist, name='add_to_watchlist'),
    path('watchlist/<int:pk>/delete/', views.delete_from_watchlist, name='delete_from_watchlist'),
    path('portfolio/', views.portfolio_list, name='portfolio_list'),
    path('portfolio/scan/', views.portfolio_scan, name='portfolio_scan'),
    path('portfolio/add/', views.add_to_portfolio, name='add_to_portfolio'),
    path('portfolio/<int:pk>/delete/', views.delete_from_portfolio, name='delete_from_portfolio'),
    path('portfolio/<int:pk>/sell/', views.sell_stock, name='sell_stock'),
    path('portfolio/report/', views.realized_pl_report, name='realized_pl_report'),
    path('portfolio/tithe/', views.tithe_report, name='tithe_report'),
    path('portfolio/tithe/mark-paid/', views.tithe_mark_paid, name='tithe_mark_paid'),
    path('portfolio/exit-plan/', views.portfolio_exit_plan, name='portfolio_exit_plan'),
    path('portfolio/exit-plan/ai/', views.portfolio_exit_plan_ai_analysis, name='portfolio_exit_plan_ai_analysis'),
    path('portfolio/cash/add/', views.add_cash_transaction, name='add_cash_transaction'),
    path('portfolio/fund/update/', views.update_portfolio_fund, name='update_portfolio_fund'),
    path('portfolio/fund/delete/<int:fund_id>/', views.delete_portfolio_fund, name='delete_portfolio_fund'),
    path('recommendations/', views.recommendations, name='recommendations'),
    path('us-recommendations/', views.us_recommendations, name='us_recommendations'),
    path('macro/', views.macro_economy, name='macro'),
    path('momentum/', views.momentum_scanner, name='momentum_scanner'),
    path('momentum/precision/', views.precision_momentum_scanner, name='precision_momentum_scanner'),
    path('momentum/precision/ai/', views.precision_scan_ai_analysis, name='precision_scan_ai_analysis'),
    path('momentum/precision/report/', views.precision_scan_report, name='precision_scan_report'),
    path('momentum/precision/watchlist/', views.scan_watchlist_view, name='scan_watchlist_view'),
    path('momentum/precision/watchlist/toggle/', views.watchlist_item_toggle, name='watchlist_item_toggle'),
    path('momentum/us-precision/', views.us_precision_scanner, name='us_precision_scanner'),
    path('momentum/us-precision/ai/', views.us_precision_scan_ai_analysis, name='us_precision_scan_ai_analysis'),
    path('momentum/us-precision/report/', views.us_precision_scan_report, name='us_precision_scan_report'),
    path('momentum/us-sepa/', views.us_sepa_scanner, name='us_sepa_scanner'),
    path('momentum/cup-handle/', views.cup_handle_scanner, name='cup_handle_scanner'),
    path('momentum/us-cup-handle/', views.us_cup_handle_scanner, name='us_cup_handle_scanner'),
    path('momentum/sepa/', views.minervini_sepa_scanner, name='minervini_sepa_scanner'),
    path('momentum/mean-reversion/', views.mean_reversion_scanner, name='mean_reversion_scanner'),
    path('momentum/quick-ai/<str:symbol>/', views.momentum_quick_analysis, name='momentum_quick_analysis'),
    path('momentum/us/', views.us_momentum_scanner, name='us_momentum_scanner'),
    path('momentum/us/quick-ai/<str:symbol>/', views.us_momentum_quick_analysis, name='us_momentum_quick_analysis'),
    path('momentum/us/crew/<str:symbol>/', views.us_momentum_crew_page, name='us_momentum_crew_page'),
    path('multi-factor/', views.multi_factor_scanner, name='multi_factor_scanner'),
    path('multi-factor/us/', views.us_multi_factor_scanner, name='us_multi_factor_scanner'),
    path('value/us-value/', views.us_value_scanner, name='us_value_scanner'),
    path('entry-finder/<str:symbol>/', views.entry_finder, name='entry_finder'),
    path('vcp-manual/', views.vcp_manual, name='vcp_manual'),
    path('scanner-guide/', views.scanner_guide, name='scanner_guide'),
    path('scan/turtle/', views.turtle_scanner, name='turtle_scanner'),
    path('scan/turtle/run/', views.turtle_scanner_run_ajax, name='turtle_scanner_run'),
    path('signup/', views.signup, name='signup'),
    path('scan/clear/', views.clear_scan_data, name='clear_scan_data'),
    path('scan/refresh-caps/', views.refresh_market_caps_view, name='refresh_market_caps'),
    path('morning-briefing/', views.morning_briefing, name='morning_briefing'),
    path('macro-playbook/', views.macro_playbook_view, name='macro_playbook'),
    path('macro-playbook/run/', views.macro_playbook_run_ajax, name='macro_playbook_run'),
    path('crypto-hub/', views.crypto_hub, name='crypto_hub'),
    path('chart/<str:symbol>/', views.stock_chart, name='stock_chart'),
    path('chart/<str:symbol>/data/', views.stock_chart_data, name='stock_chart_data'),
    path('gold-trading/', views.gold_trading, name='gold_trading'),
    path('crypto-trading/', views.crypto_trading, name='crypto_trading'),
    path('debug-scan/<str:symbol>/', views.debug_scan_symbol, name='debug_scan_symbol'),
    path('portfolio/refresh-prices/', views.portfolio_refresh_prices, name='portfolio_refresh_prices'),
    path('gold-trading/execute/', views.execute_gold_trade_ajax, name='execute_gold_trade'),
    path('trading-accounts/', views.trading_accounts_view, name='trading_accounts'),
    path('trading-accounts/<int:pk>/delete/', views.delete_trading_account_view, name='delete_trading_account'),
    path('trading-accounts/<int:pk>/sync/', views.sync_trading_account_ajax, name='sync_trading_account'),
    path('gold-trading/bot-status/', views.get_bot_status_ajax, name='get_bot_status'),
    path('gold-trading/positions/', views.get_gold_positions_ajax, name='get_gold_positions'),
    path('gold-trading/close-all/', views.close_all_gold_positions_ajax, name='close_all_gold_positions'),
    path('gold-trading/start-bot/', views.start_gold_bot_ajax, name='start_gold_bot'),
    path('gold-trading/stop-bot/', views.stop_gold_bot_ajax, name='stop_gold_bot'),
    path('gold-trading/history/', views.get_gold_trade_history_ajax, name='get_gold_trade_history'),
    path('gold-trading/modify-position/', views.modify_gold_position_ajax, name='modify_gold_position'),
    path('gold-trading/save-config/', views.save_gold_config_ajax, name='save_gold_config'),
    path('gold-trading/price-tick/', views.gold_price_tick_ajax, name='gold_price_tick'),

    # Investment Dashboard
    path('investment-dashboard/', views.investment_dashboard, name='investment_dashboard'),
    path('investment-dashboard/refresh/', views.investment_dashboard_refresh, name='investment_dashboard_refresh'),

    path('gold-trading/manual-exit/', views.manual_update_trade_exit, name='manual_update_trade_exit'),

    # API for External Integration (Hermes Bot)
    path('api/analysis/<str:symbol>/', views.api_stock_analysis, name='api_stock_analysis'),
]

