# Generated by Django 5.2.7 on 2025-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Asset Serial Number', max_length=100, null=True, unique=True),
        ),
    ]
