# Generated by Django 5.2.7 on 2026-02-03 08:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อลูกค้า')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อบริษัท')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='ผู้ติดต่อ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=50, verbose_name='เบอร์โทร')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อซัพพลายเออร์')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อบริษัท')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='ผู้ติดต่อ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=50, verbose_name='เบอร์โทร')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ซัพพลายเออร์',
                'verbose_name_plural': 'ซัพพลายเออร์',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='รหัสโปรเจค')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อโปรเจค')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('status', models.CharField(choices=[('DRAFT', 'Requirement Gathering'), ('SOURCING', 'Sourcing'), ('SUPPLIER_CHECK', 'Supplier Check'), ('QUOTED', 'Quotation'), ('CONTRACTED', 'Contracting'), ('ORDERING', 'Ordering'), ('RECEIVED_QC', 'Receiving/QC'), ('DELIVERY', 'Delivery'), ('ACCEPTED', 'Customer Acceptance'), ('BILLING', 'Billing'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20, verbose_name='สถานะ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มโปรเจค')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='วันที่คาดว่าจะส่งมอบ')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='วันที่ส่งมอบจริง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='pms.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'โปรเจค',
                'verbose_name_plural': 'โปรเจค',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='สถานะเดิม')),
                ('to_status', models.CharField(max_length=20, verbose_name='สถานะใหม่')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='เปลี่ยนเมื่อ')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='เปลี่ยนโดย')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pms.project', verbose_name='โปรเจค')),
            ],
            options={
                'verbose_name': 'ประวัติการเปลี่ยนสถานะ',
                'verbose_name_plural': 'ประวัติการเปลี่ยนสถานะ',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='เลขที่ใบเสนอราคา')),
                ('status', models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('SENT', 'ส่งแล้ว'), ('APPROVED', 'อนุมัติ'), ('REJECTED', 'ปฏิเสธ'), ('REVISED', 'แก้ไข')], default='DRAFT', max_length=10, verbose_name='สถานะ')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ออกใบเสนอราคา')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='ใช้ได้ถึงวันที่')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดรวม')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ส่วนลด')),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=7, max_digits=5, verbose_name='VAT (%)')),
                ('payment_terms', models.TextField(blank=True, verbose_name='เงื่อนไขการชำระเงิน')),
                ('delivery_terms', models.TextField(blank=True, verbose_name='เงื่อนไขการส่งมอบ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='pms.project', verbose_name='โปรเจค')),
            ],
            options={
                'verbose_name': 'ใบเสนอราคา',
                'verbose_name_plural': 'ใบเสนอราคา',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'สินค้า (Product)'), ('SERVICE', 'บริการ/ติดตั้ง (Service/Installation)')], default='PRODUCT', max_length=10, verbose_name='ประเภท')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อรายการ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='กรอกราคาทุนที่คำนวณแล้ว (สำหรับ Service ให้คำนวณจาก Excel ก่อน)', max_digits=12, verbose_name='ราคาทุน')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='กรอกราคาขายที่คำนวณแล้ว', max_digits=12, verbose_name='ราคาขาย')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='จำนวน')),
                ('unit', models.CharField(default='ชิ้น', max_length=50, verbose_name='หน่วย')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pms.project', verbose_name='โปรเจค')),
                ('supplier', models.ForeignKey(blank=True, help_text='ระบุเฉพาะสินค้า (Product)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_items', to='pms.supplier', verbose_name='ซัพพลายเออร์')),
            ],
            options={
                'verbose_name': 'รายการสินค้า/บริการ',
                'verbose_name_plural': 'รายการสินค้า/บริการ',
                'ordering': ['created_at'],
            },
        ),
    ]
