# Generated by Django 5.2.7 on 2026-02-03 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_delivery_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='productitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cost Price (Per Unit)'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Selling Price (Per Unit)'),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'Product (Physical Goods)'), ('SERVICE', 'Service (Labor/Installation)')], default='PRODUCT', max_length=10),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pms.project'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Optional for Services', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.supplier'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pms.customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Requirement Gathering'), ('SOURCING', 'Sourcing'), ('SUPPLIER_CHECK', 'Supplier Check'), ('QUOTED', 'Quoted'), ('CONTRACTED', 'Contracting'), ('ORDERING', 'Ordering'), ('RECEIVED_QC', 'Receiving / QC'), ('DELIVERY', 'Delivery'), ('ACCEPTED', 'Customer Acceptance'), ('BILLING', 'Billing'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ProjectStatusHistory',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
