# Generated by Django 5.2.7 on 2026-02-03 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_remove_quotation_created_by_remove_quotation_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'รายการสินค้า/บริการ', 'verbose_name_plural': 'รายการสินค้า/บริการ'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'โครงการ', 'verbose_name_plural': 'โครงการ'},
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_person',
            new_name='contact_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'สินค้า (Physical Goods)'), ('SERVICE', 'บริการ / ค่าแรง (Service)')], default='PRODUCT', max_length=10, verbose_name='ประเภท'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อรายการ'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='ระบุหากเป็นสินค้า', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.supplier', verbose_name='ซัพพลายเออร์'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ต้นทุนต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ราคาขายต่อหน่วย'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='pms.customer', verbose_name='ลูกค้า'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='กำหนดส่งมอบ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียดเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่อโครงการ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันเริ่มโครงการ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวมความต้องการ'), ('SOURCING', 'จัดหาของ'), ('SUPPLIER_CHECK', 'เช็คราคาจากซัพพลายเออร์'), ('QUOTED', 'ออกใบเสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อของ'), ('RECEIVED_QC', 'รับของ / ตรวจเช็ค'), ('DELIVERY', 'ส่งมอบงาน'), ('ACCEPTED', 'ลูกค้าตรวจรับ'), ('BILLING', 'วางบิล / เก็บเงิน'), ('CLOSED', 'ปิดโครงการ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
    ]
