# Generated by Django 5.2.7 on 2026-02-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_alter_productitem_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อเจ้าของโครงการ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทรศัพท์')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='ตำแหน่ง')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='pms.projectowner', verbose_name='เจ้าของโครงการ'),
        ),
    ]
