# Generated by Django 5.2.7 on 2026-02-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_projectowner_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวม'), ('SOURCING', 'จัดหา'), ('SUPPLIER_CHECK', 'เช็คราคา'), ('QUOTED', 'เสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อ'), ('RECEIVED_QC', 'รับของ/QC'), ('DELIVERY', 'ส่งมอบ'), ('ACCEPTED', 'ตรวจรับ'), ('BILLING', 'วางบิล'), ('CLOSED', 'ปิดจบ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.CreateModel(
            name='CustomerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='รายละเอียดความต้องการ (Voice/Text)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_converted', models.BooleanField(default=False, verbose_name='สร้างเป็นโครงการแล้ว')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_source', to='pms.project', verbose_name='โครงการที่สร้าง')),
            ],
            options={
                'verbose_name': 'ความต้องการลูกค้า (Lead)',
                'verbose_name_plural': 'ความต้องการลูกค้า (Leads)',
            },
        ),
    ]
