# Generated by Django 5.2.7 on 2026-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_alter_project_status_customerrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='job_type',
            field=models.CharField(choices=[('PROJECT', 'โครงการ (Project)'), ('SERVICE', 'งานบริการขาย (Sales Service)')], default='PROJECT', max_length=20, verbose_name='ประเภทงาน'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวม'), ('SOURCING', 'จัดหา'), ('SUPPLIER_CHECK', 'เช็คราคา'), ('QUOTED', 'เสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อ'), ('RECEIVED_QC', 'รับของ/QC'), ('DELIVERY', 'ส่งมอบ (รอคิว)'), ('ACCEPTED', 'ตรวจรับ'), ('BILLING', 'วางบิล'), ('CLOSED', 'ปิดจบ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
    ]
