# Generated by Django 5.2.7 on 2026-02-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_project_job_type_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='job_type',
            field=models.CharField(choices=[('PROJECT', 'โครงการ (Project)'), ('SERVICE', 'งานบริการขาย (Sales Service)'), ('REPAIR', 'งานแจ้งซ่อม (Repair Service)')], default='PROJECT', max_length=20, verbose_name='ประเภทงาน'),
        ),
    ]
