# Generated by Django 5.2.7 on 2026-02-10 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_alter_project_job_type'),
        ('repairs', '0003_repairjob_tracking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อทีม')),
                ('skills', models.CharField(blank=True, help_text='e.g. REPAIR,INSTALLATION,DELIVERY', max_length=255, verbose_name='ทักษะ')),
                ('max_tasks_per_day', models.PositiveIntegerField(default=5, verbose_name='งานสูงสุด/วัน')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('members', models.ManyToManyField(blank=True, related_name='service_teams', to=settings.AUTH_USER_MODEL, verbose_name='สมาชิก')),
            ],
            options={
                'verbose_name': 'ทีมบริการ',
                'verbose_name_plural': 'ทีมบริการ',
            },
        ),
        migrations.CreateModel(
            name='ServiceQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้องาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('task_type', models.CharField(choices=[('REPAIR', 'งานซ่อม'), ('INSTALLATION', 'งานติดตั้ง'), ('DELIVERY', 'งานส่งของ'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=20, verbose_name='ประเภทงาน')),
                ('priority', models.CharField(choices=[('CRITICAL', 'เร่งด่วนที่สุด'), ('HIGH', 'ด่วน'), ('NORMAL', 'ปกติ'), ('LOW', 'ไม่ด่วน')], default='NORMAL', max_length=20, verbose_name='ความเร่งด่วน')),
                ('status', models.CharField(choices=[('PENDING', 'รอจัดคิว'), ('SCHEDULED', 'จัดคิวแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสิ้น'), ('INCOMPLETE', 'ไม่เสร็จ (ยกยอด)')], default='PENDING', max_length=20, verbose_name='สถานะ')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='วันที่นัดหมาย')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='เวลานัดหมาย')),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='ชั่วโมงที่คาดว่าจะใช้')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='วันกำหนดส่ง')),
                ('ai_urgency_reason', models.TextField(blank=True, verbose_name='เหตุผลความเร่งด่วน (AI)')),
                ('completion_note', models.TextField(blank=True, verbose_name='บันทึกผลงาน')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tasks', to='pms.project', verbose_name='โครงการ')),
                ('repair_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tasks', to='repairs.repairjob', verbose_name='งานซ่อม')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='pms.serviceteam', verbose_name='ทีมรับผิดชอบ')),
            ],
            options={
                'verbose_name': 'คิวงานบริการ',
                'verbose_name_plural': 'คิวงานบริการ',
                'ordering': ['priority', 'deadline', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='หัวข้อ')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_tasks', models.ManyToManyField(blank=True, related_name='notifications', to='pms.servicequeueitem', verbose_name='งานที่เกี่ยวข้อง')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pms.serviceteam', verbose_name='ทีม')),
            ],
            options={
                'verbose_name': 'ข้อความทีม',
                'verbose_name_plural': 'ข้อความทีม',
                'ordering': ['-created_at'],
            },
        ),
    ]
