# Generated by Django 5.2.7 on 2026-02-16 03:30

import django.db.models.deletion
import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pms.models.project_file_upload_path, verbose_name='ไฟล์')),
                ('original_name', models.CharField(max_length=255, verbose_name='ชื่อไฟล์เดิม')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='คำอธิบาย')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pms.project', verbose_name='โครงการ')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pms.customerrequirement', verbose_name='ความต้องการ')),
            ],
            options={
                'verbose_name': 'ไฟล์แนบ',
                'verbose_name_plural': 'ไฟล์แนบ',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
