# Generated by Django 5.2.7 on 2026-02-16 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_add_project_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อคำขอ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('status', models.CharField(choices=[('RECEIVED', 'รับคำขอ'), ('PROCESSING', 'กำลังดำเนินการ'), ('SENT', 'ส่งคำขอ/ตอบกลับ'), ('COMPLETED', 'เสร็จสิ้น'), ('CANCELLED', 'ยกเลิก')], default='RECEIVED', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pms.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'คำขอ (Request)',
                'verbose_name_plural': 'คำขอ (Requests)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectfile',
            name='customer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pms.customerrequest', verbose_name='คำขอ'),
        ),
    ]
