# Generated by Django 5.2.7 on 2026-02-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_customerrequest_projectfile_customer_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='pms.projectowner', verbose_name='ผู้รับผิดชอบ'),
        ),
    ]
