# Generated by Django 5.2.7 on 2026-02-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_customerrequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ปิดจบงาน'),
        ),
    ]
