# Generated by Django 5.2.7 on 2026-02-21 10:31

from django.db import migrations, models


def populate_closed_at(apps, schema_editor):
    Project = apps.get_model('pms', 'Project')
    # Update projects where status is CLOSED but closed_at is null
    # We use F('updated_at') as a fallback
    Project.objects.filter(status='CLOSED', closed_at__isnull=True).update(
        closed_at=models.F('updated_at')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_project_closed_at'),
    ]

    operations = [
        migrations.RunPython(populate_closed_at),
    ]
