# Generated by Django 6.0.1 on 2026-02-21 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_populate_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อแพ็กเกจ SLA')),
                ('response_time_hours', models.PositiveIntegerField(default=4, verbose_name='เวลาตอบกลับ (ชม.)')),
                ('resolution_time_hours', models.PositiveIntegerField(default=24, verbose_name='เวลาแก้ไข (ชม.)')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดเงื่อนไข')),
            ],
            options={
                'verbose_name': 'แผน SLA',
                'verbose_name_plural': 'แผน SLA',
            },
        ),
        migrations.AddField(
            model_name='servicequeueitem',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ตอบกลับจริง'),
        ),
        migrations.AddField(
            model_name='servicequeueitem',
            name='sla_resolution_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เส้นตายการแก้ไข'),
        ),
        migrations.AddField(
            model_name='servicequeueitem',
            name='sla_response_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เส้นตายการตอบกลับ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sla_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='pms.slaplan', verbose_name='ระดับการให้บริการ (SLA)'),
        ),
    ]
