# Generated by Django 5.2.7 on 2026-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0015_slaplan_servicequeueitem_responded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.CharField(blank=True, help_text='เช่น สำนักงานใหญ่, สาขา 001', max_length=100, verbose_name='สาขา'),
        ),
        migrations.AddField(
            model_name='customer',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, verbose_name='Facebook Page/Profile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, help_text='เช่น โรงแรม, โรงงาน, หน่วยงานรัฐ', max_length=100, verbose_name='ประเภทธุรกิจ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Line ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='map_url',
            field=models.URLField(blank=True, help_text='เพื่อความสะดวกในการเดินทาง', verbose_name='ลิงก์ Google Maps'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='เช่น เงื่อนไขการเข้าพื้นที่ หรือพฤติกรรมการซื้อ', verbose_name='หมายเหตุพิเศษ/นิสัยลูกค้า'),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.CharField(blank=True, choices=[('PROSPECT', 'ลูกค้ามุ่งหวัง'), ('REGULAR', 'ลูกค้าประจำ'), ('VIP', 'ลูกค้า VIP'), ('GOVERNMENT', 'หน่วยงานรัฐ'), ('ENTERPRISE', 'องค์กรขนาดใหญ่')], max_length=50, verbose_name='กลุ่มลูกค้า'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, help_text='เช่น Facebook, Website, คนแนะนำ', max_length=100, verbose_name='ช่องทางที่รู้จักเรา'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='เลขประจำตัวผู้เสียภาษี'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่'),
        ),
    ]
