# Generated by Django 5.2.7 on 2026-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_customer_branch_customer_facebook_customer_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ตอบกลับจริง'),
        ),
        migrations.AddField(
            model_name='project',
            name='sla_resolution_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เส้นตายการแก้ไข'),
        ),
        migrations.AddField(
            model_name='project',
            name='sla_response_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เส้นตายการตอบกลับ'),
        ),
    ]
