# Generated by Django 5.2.7 on 2026-02-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_project_responded_at_project_sla_resolution_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicequeueitem',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='servicequeueitem',
            name='sla_resolution_deadline',
        ),
        migrations.RemoveField(
            model_name='servicequeueitem',
            name='sla_response_deadline',
        ),
    ]
