# Generated by Django 5.2.7 on 2026-03-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_projectstatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวม'), ('SOURCING', 'จัดหา'), ('SUPPLIER_CHECK', 'เช็คราคา'), ('QUOTED', 'เสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อ'), ('RECEIVED_QC', 'รับของ/QC'), ('INSTALLATION', 'ติดตั้ง'), ('DELIVERY', 'ส่งมอบ (รอคิว)'), ('ACCEPTED', 'ตรวจรับ'), ('BILLING', 'วางบิล'), ('WAITING_FOR_SALE_KEY', 'รอคีย์ขาย'), ('CLOSED', 'ปิดจบ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('PROJECT', 'โครงการ (Project)'), ('SERVICE', 'งานบริการขาย (Sales Service)'), ('REPAIR', 'งานแจ้งซ่อม (Repair Service)')], max_length=20)),
                ('status_key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'สถานะงาน (Dynamic)',
                'verbose_name_plural': 'สถานะงาน (Dynamic)',
                'ordering': ['job_type', 'sort_order'],
                'unique_together': {('job_type', 'status_key')},
            },
        ),
    ]
