# Generated by Django 5.2.7 on 2026-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0020_alter_project_status_jobstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='job_type',
            field=models.CharField(choices=[('PROJECT', 'โครงการ (Project)'), ('SERVICE', 'งานบริการขาย (Sales Service)'), ('REPAIR', 'งานแจ้งซ่อม (Repair Service)'), ('RENTAL', 'งานเช่า (Rental Service)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='job_type',
            field=models.CharField(choices=[('PROJECT', 'โครงการ (Project)'), ('SERVICE', 'งานบริการขาย (Sales Service)'), ('REPAIR', 'งานแจ้งซ่อม (Repair Service)'), ('RENTAL', 'งานเช่า (Rental Service)')], default='PROJECT', max_length=20, verbose_name='ประเภทงาน'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวม'), ('SOURCING', 'จัดหา'), ('SUPPLIER_CHECK', 'เช็คราคา'), ('QUOTED', 'เสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อ'), ('RECEIVED_QC', 'รับของ/QC'), ('INSTALLATION', 'ติดตั้ง'), ('DELIVERY', 'ส่งมอบ (รอคิว)'), ('ACCEPTED', 'ตรวจรับ'), ('BILLING', 'วางบิล'), ('WAITING_FOR_SALE_KEY', 'รอคีย์ขาย'), ('RENTING', 'เช่า'), ('CLOSED', 'ปิดจบ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
    ]
