# Generated by Django 5.2.7 on 2026-03-03 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0021_alter_jobstatus_job_type_alter_project_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='pms.jobstatus', verbose_name='สถานะงาน')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ (ดึงจากระบบ)')),
            ],
            options={
                'verbose_name': 'ผู้รับผิดชอบตามสถานะ',
                'verbose_name_plural': 'ผู้รับผิดชอบตามสถานะ',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='หัวข้อ')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pms.project', verbose_name='งานที่เกี่ยวข้อง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'แจ้งเตือนรายบุคคล',
                'verbose_name_plural': 'แจ้งเตือนรายบุคคล',
                'ordering': ['-created_at'],
            },
        ),
    ]
