# Generated by Django 5.2.7 on 2026-03-03 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0022_jobstatusassignment_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.CharField(max_length=50, verbose_name='รหัสสถานะ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_assignments', to='pms.project', verbose_name='โครงการ')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ')),
            ],
            options={
                'verbose_name': 'ผู้รับผิดชอบงานตามโครงการ',
                'verbose_name_plural': 'ผู้รับผิดชอบงานตามโครงการ',
                'unique_together': {('project', 'status_key')},
            },
        ),
    ]
