# Generated by Django 5.2.7 on 2026-03-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0024_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวม'), ('SOURCING', 'จัดหา'), ('SUPPLIER_CHECK', 'เช็คราคา'), ('QUOTED', 'เสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อ'), ('RECEIVED_QC', 'รับของ/QC'), ('REPAIRING', 'ซ่อม'), ('REQUESTING', 'ขอดำเนินการ'), ('INSTALLATION', 'คิว'), ('DELIVERY', 'คิว'), ('ACCEPTED', 'ตรวจรับ'), ('BILLING', 'วางบิล'), ('WAITING_FOR_SALE_KEY', 'รอคีย์ขาย'), ('RENTING', 'เช่า'), ('CLOSED', 'ปิดจบ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='servicequeueitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอจัดคิว'), ('SCHEDULED', 'จัดคิวแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสิ้น'), ('INCOMPLETE', 'ไม่เสร็จ (ยกยอด)'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=20, verbose_name='สถานะ'),
        ),
    ]
