# Generated by Django 5.2.7 on 2026-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0025_alter_project_status_alter_servicequeueitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceteam',
            name='google_chat_webhook',
            field=models.URLField(blank=True, help_text='URL สำหรับส่งแจ้งเตือนเข้าช่อง Google Chat', verbose_name='Google Chat Webhook'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='line_token',
            field=models.CharField(blank=True, help_text='LINE Notify Token สำหรับส่งแจ้งเตือน', max_length=255, verbose_name='LINE Token'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวม'), ('SOURCING', 'จัดหา'), ('SUPPLIER_CHECK', 'เช็คราคา'), ('QUOTED', 'เสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อ'), ('RECEIVED_QC', 'รับของ/QC'), ('REPAIRING', 'ซ่อม'), ('REQUESTING_ACTION', 'ขอดำเนินการ'), ('INSTALLATION', 'คิว'), ('DELIVERY', 'คิว'), ('ACCEPTED', 'ตรวจรับ'), ('BILLING', 'วางบิล'), ('WAITING_FOR_SALE_KEY', 'รอคีย์ขาย'), ('RENTING', 'เช่า'), ('CLOSED', 'ปิดจบ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
    ]
