# Generated by Django 5.2.7 on 2026-03-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0026_serviceteam_google_chat_webhook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='project',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='servicequeueitem',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
    ]
