# Generated by Django 5.2.7 on 2026-03-10 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0027_customerrequest_remarks_project_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='สถานะเดิม')),
                ('new_status', models.CharField(max_length=20, verbose_name='สถานะใหม่')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่เปลี่ยน')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ทำการเปลี่ยน')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='pms.customerrequest', verbose_name='คำขอ')),
            ],
            options={
                'verbose_name': 'ประวัติคำขอ',
                'verbose_name_plural': 'ประวัติคำขอ',
                'ordering': ['-changed_at'],
            },
        ),
    ]
