# Generated by Django 5.2.7 on 2026-03-10 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0028_requeststatuslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatusassignment',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='projectstatusassignment',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='jobstatusassignment',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ (ดึงจากระบบ)'),
        ),
        migrations.AddField(
            model_name='projectstatusassignment',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ'),
        ),
    ]
