# Generated by Django 6.0.1 on 2026-03-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0029_remove_jobstatusassignment_responsible_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianGPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('CHECK_IN', 'เริ่มงาน (Check-in)'), ('ON_SITE', 'ถึงที่หน้างาน (On-site)'), ('TRAVEL', 'กำลังเดินทาง (Travel)'), ('CHECK_OUT', 'เสร็จงาน (Check-out)')], default='ON_SITE', max_length=20, verbose_name='ประเภทการเช็คอิน')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12, verbose_name='ละติจูด')),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12, verbose_name='ลองจิจูด')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อสถานที่')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาเช็คอิน')),
                ('queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_logs', to='pms.servicequeueitem', verbose_name='งานที่เกี่ยวข้อง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to=settings.AUTH_USER_MODEL, verbose_name='ช่าง')),
            ],
            options={
                'verbose_name': 'GPS Log ช่าง',
                'verbose_name_plural': 'GPS Logs ช่าง',
                'ordering': ['timestamp'],
            },
        ),
    ]
