# Generated by Django 6.0.1 on 2026-03-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0030_technician_gps_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicequeueitem',
            name='assigned_team',
        ),
        migrations.AddField(
            model_name='servicequeueitem',
            name='assigned_teams',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='pms.serviceteam', verbose_name='ทีมรับผิดชอบ'),
        ),
    ]
