# Generated by Django 6.0.1 on 2026-03-16 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0031_servicequeueitem_multi_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('VERY_SATISFIED', 'พอใจมาก'), ('SATISFIED', 'พอใจ'), ('NOT_SATISFIED', 'ไม่พอใจ')], max_length=20, verbose_name='ความพอใจ')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='ชื่อลูกค้า')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาประเมิน')),
                ('gps_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='pms.techniciangpslog', verbose_name='GPS Log (Check-out)')),
            ],
            options={
                'verbose_name': 'ประเมินความพอใจลูกค้า',
                'verbose_name_plural': 'ประเมินความพอใจลูกค้า',
                'ordering': ['-created_at'],
            },
        ),
    ]
