# Generated by Django 6.0.1 on 2026-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0032_customer_satisfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciangpslog',
            name='check_type',
            field=models.CharField(choices=[('GO_WORK', 'ออกทำงาน (Go Work)'), ('ON_SITE', 'เริ่มงาน (On-site)'), ('CHECK_OUT', 'เสร็จงาน (Check-out)'), ('BACK_OFFICE', 'กลับที่ทำงาน (Back to Office)'), ('TRAVEL', 'กำลังเดินทาง (Auto-Track)'), ('CHECK_IN', 'เริ่มงาน (Check-in)')], default='ON_SITE', max_length=20, verbose_name='ประเภทการเช็คอิน'),
        ),
    ]
