# Generated by Django 6.0.1 on 2026-03-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0033_gps_new_check_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวม'), ('SOURCING', 'จัดหา'), ('SUPPLIER_CHECK', 'เช็คราคา'), ('QUOTED', 'เสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อ'), ('RECEIVED_QC', 'รับของ/QC'), ('REPAIRING', 'ซ่อม'), ('REQUESTING_ACTION', 'ขอดำเนินการ'), ('INSTALLATION', 'คิว'), ('DELIVERY', 'คิว'), ('PREPARING_DOCS', 'เตรียมเอกสารใบส่งสินค้า'), ('ACCEPTED', 'ตรวจรับ'), ('BILLING', 'วางบิล'), ('WAITING_FOR_SALE_KEY', 'รอคีย์ขาย'), ('RENTING', 'เช่า'), ('CLOSED', 'ปิดจบ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
    ]
