# Generated by Django 6.0.1 on 2026-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0037_remove_jobstatus_triggers_ai_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อทักษะ')),
                ('skill_type', models.CharField(choices=[('REPAIR', 'งานซ่อม'), ('INSTALLATION', 'งานติดตั้ง'), ('DELIVERY', 'งานส่งของ'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=20, verbose_name='ประเภทงาน')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'ทักษะ',
                'verbose_name_plural': 'ทักษะ',
                'ordering': ['skill_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ละติจูด (Latitude)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ลองจิจูด (Longitude)'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='base_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='ที่อยู่ฐาน'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ละติจูด (Latitude)'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ลองจิจูด (Longitude)'),
        ),
        migrations.AlterField(
            model_name='serviceteam',
            name='skills',
            field=models.CharField(blank=True, help_text='e.g. REPAIR,INSTALLATION,DELIVERY (legacy)', max_length=255, verbose_name='ทักษะ (เดิม)'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='team_skills',
            field=models.ManyToManyField(blank=True, related_name='teams', to='pms.skill', verbose_name='ทักษะ'),
        ),
    ]
