# Generated by Django 6.0.1 on 2026-04-04 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0039_alter_jobstatus_job_type_alter_project_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianTrackingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_track', models.BooleanField(default=False, verbose_name='บังคับ Auto-Track')),
                ('forced_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่เปิด')),
                ('toggled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ปิด/เปิดโดย')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_state', to=settings.AUTH_USER_MODEL, verbose_name='ช่าง')),
            ],
            options={
                'verbose_name': 'สถานะ Auto-Track ช่าง',
                'verbose_name_plural': 'สถานะ Auto-Track ช่าง',
            },
        ),
    ]
