# Generated by Django 6.0.1 on 2026-04-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0040_tracking_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciangpslog',
            name='accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='ความแม่นยำ (เมตร)'),
        ),
    ]
