# Generated by Django 5.2.7 on 2026-04-09 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0041_techniciangpslog_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciangpslog',
            name='accuracy',
        ),
    ]
