# Generated by Django 5.2.7 on 2026-04-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0042_remove_techniciangpslog_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='job_type',
            field=models.CharField(choices=[('PROJECT', 'โครงการ (Project)'), ('SERVICE', 'งานบริการขาย (Sales Service)'), ('REPAIR', 'งานแจ้งซ่อม (Repair Service)'), ('RENTAL', 'งานเช่า (Rental Service)'), ('SURVEY', 'งานดูหน้างาน (Site Survey)'), ('GENERAL', 'งานทั่วไป (General)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='job_type',
            field=models.CharField(choices=[('PROJECT', 'โครงการ (Project)'), ('SERVICE', 'งานบริการขาย (Sales Service)'), ('REPAIR', 'งานแจ้งซ่อม (Repair Service)'), ('RENTAL', 'งานเช่า (Rental Service)'), ('SURVEY', 'งานดูหน้างาน (Site Survey)'), ('GENERAL', 'งานทั่วไป (General)')], default='PROJECT', max_length=20, verbose_name='ประเภทงาน'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'รวบรวม'), ('SOURCING', 'จัดหา'), ('SUPPLIER_CHECK', 'เช็คราคา'), ('QUOTED', 'เสนอราคา'), ('CONTRACTED', 'ทำสัญญา'), ('ORDERING', 'สั่งซื้อ'), ('RECEIVED_QC', 'รับของ/QC'), ('REPAIRING', 'ซ่อม'), ('REQUESTING_ACTION', 'ขอดำเนินการ'), ('INSTALLATION', 'คิว'), ('DELIVERY', 'คิว'), ('PREPARING_DOCS', 'เตรียมเอกสารใบส่งสินค้า'), ('QUEUE_SURVEY', 'รอเข้าคิวดูหน้างาน'), ('QUEUE_GENERAL', 'รอเข้าคิวงานทั่วไป'), ('ACCEPTED', 'ตรวจรับ'), ('BILLING', 'วางบิล'), ('WAITING_FOR_SALE_KEY', 'รอคีย์ขาย'), ('RENTING', 'เช่า'), ('CLOSED', 'ปิดจบ'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='servicequeueitem',
            name='task_type',
            field=models.CharField(choices=[('REPAIR', 'งานซ่อม'), ('INSTALLATION', 'งานติดตั้ง'), ('DELIVERY', 'งานส่งของ'), ('SURVEY', 'ดูหน้างาน/สำรวจ'), ('GENERAL', 'งานทั่วไป'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=20, verbose_name='ประเภทงาน'),
        ),
    ]
