# Generated by Django 5.2.7 on 2026-05-05 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0043_add_general_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='ชื่อลูกค้า/บริษัท')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='ชื่อผู้ติดต่อ')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทรศัพท์')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='Line ID')),
                ('project_interested', models.CharField(blank=True, max_length=255, verbose_name='โครงการ/สินค้าที่สนใจ')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ประมาณการยอดขาย')),
                ('interest_level', models.CharField(choices=[('HOT', '🔥 Hot (สนใจมาก - พร้อมปิด)'), ('WARM', '☀️ Warm (สนใจ - รอติดตาม)'), ('COLD', '❄️ Cold (สนใจน้อย - เก็บข้อมูล)')], default='WARM', max_length=10, verbose_name='ระดับความสนใจ')),
                ('status', models.CharField(choices=[('PROSPECT', 'ผู้มุ่งหวังใหม่'), ('QUALIFIED', 'ผ่านเกณฑ์/สนใจจริง'), ('CONVERTED', 'แปลงเป็นโครงการแล้ว'), ('LOST', 'ยกเลิก/ไม่สนใจ')], default='PROSPECT', max_length=20, verbose_name='สถานะ Lead')),
                ('source', models.CharField(blank=True, help_text='เช่น ไปพบเอง, คนแนะนำ', max_length=100, verbose_name='ช่องทางที่ได้มา')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่/พิกัดลูกค้า')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='pms.project', verbose_name='โครงการที่สร้างขึ้น')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to=settings.AUTH_USER_MODEL, verbose_name='พนักงานขายผู้รับผิดชอบ')),
            ],
            options={
                'verbose_name': 'ผู้มุ่งหวัง (Sales Lead)',
                'verbose_name_plural': 'ผู้มุ่งหวัง (Sales Leads)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('VISIT', 'เข้าพบลูกค้า (Site Visit)'), ('CALL', 'โทรศัพท์ (Phone Call)'), ('LINE', 'ติดต่อทาง Line'), ('PRESENT', 'นำเสนอแผนงาน/Demo'), ('OTHER', 'อื่นๆ')], default='VISIT', max_length=20, verbose_name='ประเภทกิจกรรม')),
                ('note', models.TextField(verbose_name='บันทึกรายละเอียด')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='สถานที่/เช็คอิน')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='วันนัดหมายครั้งถัดไป')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pms.saleslead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'บันทึกกิจกรรมการขาย',
                'verbose_name_plural': 'บันทึกกิจกรรมการขาย',
                'ordering': ['-created_at'],
            },
        ),
    ]
