# Generated by Django 5.2.7 on 2026-05-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0044_saleslead_salesactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleslead',
            name='converted_project',
        ),
        migrations.RemoveField(
            model_name='saleslead',
            name='salesperson',
        ),
        migrations.AlterModelOptions(
            name='customerrequirement',
            options={'verbose_name': 'ความต้องการลูกค้า (Lead เดิม)', 'verbose_name_plural': 'ความต้องการลูกค้า (Leads เดิม)'},
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='ชื่อบริษัท/ลูกค้า')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='ผู้ติดต่อหลัก')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('location', models.CharField(blank=True, help_text='ระบุพิกัดหรือชื่อสถานที่ที่พนักงานไปหา', max_length=255, verbose_name='พิกัด/สถานที่')),
                ('source', models.CharField(choices=[('EXHIBITION', 'ออกบูธ / งานแสดงสินค้า'), ('REFERRAL', 'ลูกค้าแนะนำ (Referral)'), ('COLD_CALL', 'โทรหาลูกค้า (Cold Call)'), ('WEBSITE', 'เว็บไซต์บริษัท'), ('SOCIAL', 'Social Media (FB/Line)'), ('OUTSIDE_VISIT', 'ลงพื้นที่จริง (Field Visit)'), ('OTHER', 'อื่นๆ')], default='OUTSIDE_VISIT', max_length=20, verbose_name='ช่องทางที่มา')),
                ('status', models.CharField(choices=[('NEW', 'รอนำเนินการ (New)'), ('CONTACTED', 'ติดต่อแล้ว (Contacted)'), ('QUALIFIED', 'มีศักยภาพ (Qualified)'), ('PROPOSAL', 'เสนอราคา (Proposal)'), ('NEGOTIATION', 'เจรจาต่อรอง (Negotiation)'), ('WON', 'ปิดการขายได้ (Won)'), ('LOST', 'เสียโอกาส (Lost)')], default='NEW', max_length=20, verbose_name='สถานะ Lead')),
                ('interest_score', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=3, verbose_name='ระดับความสนใจ')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='งบประมาณประมาณการ')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='วันที่คาดว่าจะปิดการขาย')),
                ('notes', models.TextField(blank=True, verbose_name='รายละเอียดการพูดคุย / ความต้องการ')),
                ('is_converted', models.BooleanField(default=False, verbose_name='แปลงเป็นโครงการแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='pms.projectowner', verbose_name='พนักงานผู้รับผิดชอบ')),
                ('converted_project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origin', to='pms.project', verbose_name='โครงการที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'ผู้มุ่งหวัง (Lead)',
                'verbose_name_plural': 'ผู้มุ่งหวัง (Leads)',
                'ordering': ['-interest_score', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SalesActivity',
        ),
        migrations.DeleteModel(
            name='SalesLead',
        ),
    ]
