# Generated by Django 6.0.1 on 2026-05-07 08:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0045_remove_saleslead_converted_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ไม่อนุมัติ')], default='DRAFT', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tech_equip_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ต้นทุนอุปกรณ์ติดตั้ง')),
                ('tech_risk', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าความเสี่ยง/ค่ายขนนำไฟ')),
                ('tech_fuel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าน้ำมันรถบริการ')),
                ('tech_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าเสื่อมรถบริการ')),
                ('tech_travel', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ที่พัก/ค่าคอมช่าง')),
                ('tech_misc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าใช้จ่ายอื่นๆ')),
                ('tech_hidden_labor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าแรงแฝง')),
                ('tech_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าประกันสัญญา')),
                ('tech_days', models.PositiveSmallIntegerField(default=1, verbose_name='จำนวนวัน')),
                ('tech_people', models.PositiveSmallIntegerField(default=1, verbose_name='จำนวนคน')),
                ('tech_labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าแรงต่อคนต่อวัน')),
                ('tech_splice', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่า Splice สาย F.O')),
                ('mkt_product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ต้นทุนสินค้าขาย')),
                ('mkt_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('1.85'), max_digits=5, verbose_name='อัตราดอกเบี้ย/เดือน (%)')),
                ('mkt_rebate_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ส่วนคืนหน่วยงาน (ต้นทุน)')),
                ('mkt_price_adjust', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ปรับเพิ่มอุปกรณ์ราคาแนะนำ')),
                ('mkt_checkup', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='งานเช็คอีฟระบบ')),
                ('mkt_variable', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='อื่นๆ (ส่วนแปรผัน)')),
                ('mkt_service', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='งานบริการ')),
                ('mkt_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ส่วนลด')),
                ('mkt_rebate_sell', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เพิ่มคืนส่วนหน่วยงาน')),
                ('proposal_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคาเสนอ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ประเมิน')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimation', to='pms.project')),
            ],
            options={
                'verbose_name': 'ใบประเมินงาน',
                'verbose_name_plural': 'ใบประเมินงาน',
            },
        ),
    ]
