# Generated by Django 6.0.1 on 2026-05-08 08:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0046_project_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimation',
            name='tech_bank_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='อัตราดอกเบี้ยธนาคาร (%/ปี)'),
        ),
        migrations.AddField(
            model_name='projectestimation',
            name='tech_contract_years',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4, verbose_name='จำนวนปีสัญญา'),
        ),
    ]
