# Generated by Django 6.0.1 on 2026-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0047_add_insurance_calc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimation',
            name='tech_hidden_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='อัตราค่าแรงแฝง/วัน/คน'),
        ),
    ]
