# Generated by Django 5.2.7 on 2026-09-16 03:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อชิ้นงานโฆษณา (Ad Name)')),
                ('format', models.CharField(choices=[('video', 'วิดีโอสั้น / Reels / TikTok (Video)'), ('image', 'รูปภาพเดี่ยว (Single Image)'), ('carousel', 'ภาพชุด / แคตตาล็อก (Carousel)'), ('story', 'สตอรี่แนวตั้ง (Story)')], default='video', max_length=20, verbose_name='รูปแบบชิ้นงาน')),
                ('hook_text', models.TextField(blank=True, help_text='ประโยคเปิดคลิปหรือคำพาดหัวบนรูปภาพ', verbose_name='Hook 3 วินาทีแรก / พาดหัว')),
                ('angle', models.CharField(blank=True, help_text='เช่น ปัญหาผิว, เทียบกับคู่แข่ง, โปรโมชั่น', max_length=150, verbose_name='มุมการขาย (Angle)')),
                ('status', models.CharField(choices=[('winner', '🚀 ตัวทำเงิน (Winner - Scale Up)'), ('testing', '⚡ กำลังทดสอบ (Testing)'), ('fatigued', '⚠️ แอดเริ่มล้า (Fatigued - Need Refresh)'), ('killed', '🛑 ปิดใช้งาน (Killed - Underperformed)')], default='testing', max_length=20, verbose_name='สถานะประสิทธิภาพ')),
                ('media_url', models.CharField(blank=True, max_length=500, verbose_name='ลิงก์ไฟล์ชิ้นงาน / รหัส Ads')),
                ('notes', models.TextField(blank=True, verbose_name='บันทึกข้อสังเกต')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
            ],
            options={
                'verbose_name': 'ชิ้นงานโฆษณา (Creative)',
                'verbose_name_plural': 'ชิ้นงานโฆษณา (Creatives)',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ประเมิน')),
                ('title', models.CharField(default='AI Daily Action Plan', max_length=200, verbose_name='หัวข้อแผนงาน')),
                ('status_level', models.CharField(choices=[('healthy', '🟢 สุขภาพพอร์ตดีเยี่ยม (Scaling Mode)'), ('warning', '🟡 ควรปรับปรุงเร่งด่วน (Adjustment Needed)'), ('critical', '🔴 ขาดทุน/ต้องหยุดเลือดไหล (Loss Prevention)')], default='healthy', max_length=20, verbose_name='ระดับสุขภาพแคมเปญ')),
                ('executive_summary', models.TextField(verbose_name='บทสรุปสำหรับผู้บริหาร (Executive Summary)')),
                ('total_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ค่าแอดรวม')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ยอดขายรวม')),
                ('overall_roas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='ROAS เฉลี่ย')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='กำไรสุทธิรวม')),
                ('scale_recommendations', models.JSONField(blank=True, default=list, verbose_name='แอดที่ควรสเกลเพิ่มงบ (Scale List)')),
                ('kill_recommendations', models.JSONField(blank=True, default=list, verbose_name='แอดที่ควรปิดทันที (Kill List)')),
                ('creative_fatigue_alerts', models.JSONField(blank=True, default=list, verbose_name='แอดที่เริ่มล้า (Fatigue Alerts)')),
                ('action_items', models.JSONField(blank=True, default=list, verbose_name='Checklist งานที่ต้องทำวันนี้')),
                ('ai_model_name', models.CharField(default='Google Gemini 2.5/3.0', max_length=100, verbose_name='โมเดลที่ใช้')),
                ('raw_ai_response', models.TextField(blank=True, verbose_name='ข้อความดิบจาก AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่สร้าง')),
            ],
            options={
                'verbose_name': 'แผนปฏิบัติการ AI (Action Plan)',
                'verbose_name_plural': 'แผนปฏิบัติการ AI (Action Plans)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorIntel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=150, verbose_name='ชื่อแบรนด์คู่แข่ง')),
                ('platform', models.CharField(default='Facebook / TikTok', max_length=50, verbose_name='ช่องทางที่พบ')),
                ('ad_or_post_url', models.CharField(blank=True, max_length=500, verbose_name='ลิงก์โพสต์/แอดของคู่แข่ง')),
                ('hook_observed', models.TextField(blank=True, verbose_name='Hook หรือจุดขายที่คู่แข่งใช้')),
                ('pricing_promotion', models.CharField(blank=True, max_length=255, verbose_name='ราคา / โปรโมชั่นของเขา')),
                ('ai_counter_strategy', models.TextField(blank=True, verbose_name='กลยุทธ์แก้เกมที่ AI แนะนำ')),
                ('observed_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ตรวจพบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลคู่แข่ง (Competitor Intel)',
                'verbose_name_plural': 'ข้อมูลคู่แข่ง (Competitor Intel)',
                'ordering': ['-observed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='สินค้า / บริการ')),
                ('target_persona', models.CharField(max_length=200, verbose_name='กลุ่มลูกค้าเป้าหมาย')),
                ('angle_theme', models.CharField(max_length=200, verbose_name='ธีม / มุมขายหลัก')),
                ('hook_options', models.JSONField(blank=True, default=list, verbose_name='ตัวเลือก Hook 3 วินาทีแรก (5 แบบ)')),
                ('script_outline', models.TextField(blank=True, verbose_name='โครงเรื่องสคริปต์วิดีโอ (Hook -> Pain -> Solution -> CTA)')),
                ('caption_copy', models.TextField(blank=True, verbose_name='ข้อความแคปชั่นพร้อมโพสต์')),
                ('format', models.CharField(choices=[('tiktok_reels', 'TikTok / Instagram Reels (9:16 แนวตั้ง)'), ('fb_video', 'Facebook Video Post (1:1 หรือ 4:5)'), ('carousel', 'Carousel Post สไลด์ภาพ'), ('direct_response', 'Direct-Response Long Copy (โพสต์ปิดการขาย)')], default='tiktok_reels', max_length=30, verbose_name='รูปแบบ')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='ชิ้นงานโปรด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่คิดค้น')),
            ],
            options={
                'verbose_name': 'ไอเดียและสคริปต์โฆษณา AI',
                'verbose_name_plural': 'ไอเดียและสคริปต์โฆษณา AI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อแคมเปญ')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook / Instagram)'), ('tiktok', 'TikTok Ads'), ('google', 'Google Ads / YouTube'), ('line', 'LINE Ads'), ('shopee', 'Shopee Ads'), ('lazada', 'Lazada Ads'), ('other', 'ช่องทางอื่น ๆ')], default='meta', max_length=20, verbose_name='แพลตฟอร์ม')),
                ('objective', models.CharField(choices=[('conversions', 'ยอดขาย / ปิดการขาย (Conversions)'), ('messages', 'ทักแชท / ข้อความ (Messages)'), ('leads', 'กรอกฟอร์ม / ผู้สนใจ (Leads)'), ('traffic', 'เข้าชมเว็บไซต์ (Traffic)'), ('brand', 'การรับรู้แบรนด์ (Brand Awareness)')], default='conversions', max_length=30, verbose_name='วัตถุประสงค์')),
                ('status', models.CharField(choices=[('active', 'กำลังเปิดใช้งาน (Active)'), ('paused', 'หยุดชั่วคราว (Paused)'), ('ended', 'สิ้นสุดแล้ว (Ended)')], default='active', max_length=20, verbose_name='สถานะ')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='งบประมาณรายวัน (บาท)')),
                ('target_roas', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='เป้าหมาย ROAS (เท่า)')),
                ('target_audience', models.TextField(blank=True, verbose_name='กลุ่มเป้าหมาย (Audience)')),
                ('product_focus', models.CharField(blank=True, max_length=200, verbose_name='สินค้าหลักในแคมเปญ')),
                ('notes', models.TextField(blank=True, verbose_name='บันทึกเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
            ],
            options={
                'verbose_name': 'แคมเปญโฆษณา',
                'verbose_name_plural': 'แคมเปญโฆษณา',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook / Instagram)'), ('tiktok', 'TikTok Ads'), ('google', 'Google Ads / YouTube'), ('line', 'LINE Ads'), ('shopee', 'Shopee Ads'), ('lazada', 'Lazada Ads'), ('other', 'ช่องทางอื่น ๆ')], default='meta', max_length=20, verbose_name='ช่องทาง')),
                ('ad_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ค่าโฆษณา (บาท)')),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ยอดขายที่ได้รับ (บาท)')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='จำนวนคำสั่งซื้อ / ลูกค้า (Orders)')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='จำนวนการมองเห็น (Impressions)')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='จำนวนคลิก (Clicks)')),
                ('cogs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ต้นทุนสินค้า (COGS)')),
                ('other_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ค่าส่ง/แพ็ก/ธรรมเนียม')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='บันทึกย่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='marketing.adcreative', verbose_name='ชิ้นงานโฆษณา')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='marketing.marketingcampaign', verbose_name='แคมเปญ')),
            ],
            options={
                'verbose_name': 'สถิติผลการตลาดรายวัน',
                'verbose_name_plural': 'สถิติผลการตลาดรายวัน',
                'ordering': ['-date', '-ad_spend'],
            },
        ),
        migrations.AddField(
            model_name='adcreative',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='marketing.marketingcampaign', verbose_name='แคมเปญ'),
        ),
    ]
