# Generated by Django 5.2.7 on 2026-03-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms', '0029_remove_jobstatusassignment_responsible_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อห้อง')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('color_hex', models.CharField(default='#3b82f6', max_length=7, verbose_name='สีประจำห้อง (Hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='pms.project', verbose_name='โครงการที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'ห้องแชท',
                'verbose_name_plural': 'ห้องแชท',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='ข้อความ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลาส่ง')),
                ('is_speech_to_text', models.BooleanField(default=False, verbose_name='ส่งด้วยเสียง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่ง')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='ห้องแชท')),
            ],
            options={
                'verbose_name': 'ข้อความแชท',
                'verbose_name_plural': 'ข้อความแชท',
                'ordering': ['timestamp'],
            },
        ),
    ]
