# Generated by Django 5.2.7 on 2026-03-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'permissions': [('can_chat', 'สามารถเข้าใช้งานระบบแชทกลาง')], 'verbose_name': 'ห้องแชท', 'verbose_name_plural': 'ห้องแชท'},
        ),
    ]
