# Generated by Django 5.2.7 on 2026-03-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/', verbose_name='ไฟล์แนบ'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/%Y/%m/', verbose_name='รูปภาพ'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='ละติจูด'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อสถานที่'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='ลองจิจูด'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, verbose_name='ข้อความ'),
        ),
    ]
