# Generated by Django 5.2.7 on 2026-03-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_file_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='app_category',
            field=models.CharField(choices=[('general', 'ส่วนกลาง (General)'), ('rentals', 'ระบบสัญญาเช่า (Rentals)'), ('repairs', 'ระบบงานซ่อม (Repairs)'), ('pms', 'ระบบบริหารโครงการ (PMS)'), ('payroll', 'ระบบเงินเดือน (Payroll)')], default='general', max_length=20, verbose_name='หมวดหมู่ระบบ'),
        ),
    ]
