# Generated by Django 5.2.7 on 2026-03-11 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_app_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้ที่ได้รับอนุญาต'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='ห้องส่วนตัว (จำกัดสิทธิ์)'),
        ),
    ]
