# Generated by Django 6.0.1 on 2026-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_allowed_users_chatroom_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_html',
            field=models.BooleanField(default=False, verbose_name='เนื้อหาเป็น HTML'),
        ),
    ]
