# Generated by Django 6.0.1 on 2026-03-19 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_message_is_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อลูกค้า'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรลูกค้า'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='customer_rating',
            field=models.CharField(blank=True, max_length=20, verbose_name='ผลประเมินลูกค้า'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='gps_check_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='ประเภท GPS Check'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_preview',
            field=models.CharField(blank=True, max_length=150, verbose_name='ตัวอย่างข้อความที่ตอบกลับ'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage', verbose_name='ข้อความที่ตอบกลับ'),
        ),
    ]
