# Generated by Django 5.2.7 on 2026-04-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_customer_name_chatmessage_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='app_category',
            field=models.CharField(choices=[('general', 'ส่วนกลาง (General)'), ('rentals', 'ระบบสัญญาเช่า (Rentals)'), ('repairs', 'ระบบงานซ่อม (Repairs)'), ('pms', 'ระบบบริหารโครงการ (PMS)'), ('payroll', 'ระบบเงินเดือน (Payroll)'), ('stocks', 'ระบบวิเคราะห์หุ้น (Stocks)')], default='general', max_length=20, verbose_name='หมวดหมู่ระบบ'),
        ),
    ]
