# Generated by Django 5.2.7 on 2026-03-12 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'ผู้ดูแลระบบ (Admin)'), ('manager', 'ผู้บริหาร (Manager)'), ('reception', 'แอดมินรับงาน (Reception)'), ('technician_lead', 'หัวหน้าช่าง (Lead Technician)'), ('technician', 'ช่างเทคนิค (Technician)'), ('sale', 'พนักงานขาย (Sale)'), ('hr_payroll', 'ฝ่ายบุคคล/เงินเดือน (HR/Payroll)')], default='technician', max_length=20, verbose_name='ตำแหน่ง/บทบาท')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'โปรไฟล์พนักงาน',
                'verbose_name_plural': 'โปรไฟล์พนักงาน',
            },
        ),
    ]
