# Generated by Django 5.2.7 on 2026-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_chat',
            field=models.BooleanField(default=True, verbose_name='เข้าใช้ศูนย์แชทกลาง'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_payroll',
            field=models.BooleanField(default=False, verbose_name='เข้าใช้ระบบเงินเดือน'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_pms',
            field=models.BooleanField(default=False, verbose_name='เข้าใช้ระบบจัดการโครงการ (PMS)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_pos',
            field=models.BooleanField(default=False, verbose_name='เข้าใช้ระบบขายสินค้า (POS)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_rentals',
            field=models.BooleanField(default=False, verbose_name='เข้าใช้ระบบสัญญาเช่า'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_repairs',
            field=models.BooleanField(default=True, verbose_name='เข้าใช้ระบบซ่อมบำรุง'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_stocks',
            field=models.BooleanField(default=False, verbose_name='เข้าใช้ระบบวิเคราะห์หุ้น AI'),
        ),
    ]
