# Generated by Django 5.2.7 on 2026-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_access_chat_userprofile_access_payroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_accounts',
            field=models.BooleanField(default=False, verbose_name='เข้าใช้ระบบจัดการพนักงาน (User Management)'),
        ),
    ]
