# Generated by Django 6.0.1 on 2026-03-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_access_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ตัวพิมพ์เล็ก ไม่มีช่องว่าง เช่น technician, manager', max_length=30, unique=True, verbose_name='รหัสตำแหน่ง')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อตำแหน่ง')),
                ('is_staff_role', models.BooleanField(default=False, help_text='เปิดใช้: เห็นข้อมูลทุกคนในรายงาน + เข้า /admin ได้', verbose_name='สิทธิ์ดูแลระบบ (Staff)')),
                ('is_technician_role', models.BooleanField(default=False, help_text='เปิดใช้: แสดงปุ่ม GPS ในห้องแชท', verbose_name='เป็นตำแหน่งช่าง (GPS)')),
                ('badge_color', models.CharField(default='bg-slate-100 text-slate-800 border-slate-200', max_length=200, verbose_name='CSS Badge (Tailwind classes)')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับการแสดง')),
            ],
            options={
                'verbose_name': 'ตำแหน่ง/บทบาท',
                'verbose_name_plural': 'ตำแหน่ง/บทบาท',
                'ordering': ['order', 'name'],
            },
        ),
    ]
