# Generated by Django 6.0.1 on 2026-03-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_populate_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_view_all_reports',
            field=models.BooleanField(default=False, help_text='เปิดใช้: ดูข้อมูล/รายงานของพนักงานทุกคนได้ (ไม่จำเป็นต้องเข้า /admin)', verbose_name='ดูรายงานของทุกคนได้'),
        ),
    ]
