# Generated by Django 6.0.1 on 2026-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_can_view_all_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='access_payroll',
            field=models.BooleanField(default=True, verbose_name='เข้าใช้ระบบเงินเดือน'),
        ),
    ]
