# Generated by Django 5.2.7 on 2026-04-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_payroll_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_ops',
            field=models.BooleanField(default=False, verbose_name='เข้าใช้ระบบวางแผน (Ops App)'),
        ),
    ]
