# Generated by Django 5.2.7 on 2026-04-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_access_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_board',
            field=models.BooleanField(default=False, verbose_name='เข้าใช้ระบบ Dashboard (Board)'),
        ),
    ]
