# Generated by Django 5.2.7 on 2026-09-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_access_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_marketing',
            field=models.BooleanField(default=True, verbose_name='เข้าใช้ระบบการตลาด AI (Marketing OS)'),
        ),
    ]
