# Generated by Django 5.2.7 on 2026-04-19 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อฝ่าย'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='ops.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อเป้าหมาย')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด/วิธีปฏิบัติ')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่ม (จันทร์)')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุด (เสาร์)')),
                ('target_value', models.FloatField(default=0, verbose_name='ตัวเลขเป้าหมาย (Target)')),
                ('unit', models.CharField(default='งาน', max_length=50, verbose_name='หน่วยวัด (บาท/งาน/โพสต์)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='ops.department')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่รายงาน')),
                ('actual_value', models.FloatField(default=0, verbose_name='จำนวนที่ทำได้จริง')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ/อุปสรรค')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ops/progress/', verbose_name='รูปภาพหน้างาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progresses', to='ops.weeklygoal')),
            ],
        ),
        migrations.DeleteModel(
            name='MeetingNote',
        ),
        migrations.DeleteModel(
            name='WeeklyAgenda',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
