# Generated by Django 5.2.7 on 2026-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_remove_task_agenda_remove_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklygoal',
            name='status',
            field=models.CharField(choices=[('todo', 'รอดำเนินการ (To Do)'), ('doing', 'กำลังทำ (In Progress)'), ('done', 'เสร็จสิ้น (Done)'), ('blocked', 'ติดปัญหา (Blocked)')], default='todo', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='weeklygoal',
            name='unit',
            field=models.CharField(default='งาน', max_length=20, verbose_name='หน่วยวัด'),
        ),
    ]
