# Generated by Django 5.2.7 on 2026-04-24 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_weeklygoal_status_alter_weeklygoal_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อการประชุม')),
                ('agenda', models.TextField(verbose_name='วาระการประชุม')),
                ('date', models.DateField(verbose_name='วันที่ประชุม')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุด')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='สถานที่/ห้องประชุม')),
                ('minutes', models.TextField(blank=True, verbose_name='บันทึกมติที่ประชุม (Real-time Minutes)')),
                ('status', models.CharField(choices=[('scheduled', 'นัดหมายแล้ว'), ('in_progress', 'กำลังประชุม'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='scheduled', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดประชุม')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อไอเดีย')),
                ('description', models.TextField(verbose_name='รายละเอียดไอเดีย')),
                ('impact_score', models.IntegerField(default=0, verbose_name='คะแนนผลกระทบ (1-10)')),
                ('feasibility_score', models.IntegerField(default=0, verbose_name='คะแนนความเป็นไปได้ (1-10)')),
                ('total_score', models.IntegerField(default=0, verbose_name='คะแนนรวม')),
                ('status', models.CharField(choices=[('proposed', 'เสนอไอเดีย'), ('under_review', 'กำลังพิจารณา'), ('approved', 'อนุมัติ (เป็นงาน)'), ('rejected', 'ปฏิเสธ')], default='proposed', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ideas', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='ops.meeting', verbose_name='การประชุม')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้เสนอไอเดีย')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่องาน')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่ม')),
                ('due_date', models.DateField(verbose_name='วันครบกำหนด')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('doing', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=10, verbose_name='สถานะ')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10, verbose_name='ความสำคัญ')),
                ('progress_pct', models.IntegerField(default=0, verbose_name='ความคืบหน้า (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.department', verbose_name='ฝ่าย')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='ops.actiontask', verbose_name='งานที่ต้องทำก่อน')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_task', to='ops.meetingidea', verbose_name='ไอเดียต้นฉบับ')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attended', models.BooleanField(default=False, verbose_name='เข้าประชุม')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ops.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
