# Generated by Django 5.2.7 on 2026-06-03 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_meeting_meetingidea_actiontask_meetingparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICoworkerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('marketing', 'Marketing Automation'), ('sales', 'Sales Intelligence'), ('executive', 'Executive Reporting')], max_length=20, verbose_name='ประเภทเอเจนต์')),
                ('input_data', models.TextField(verbose_name='ข้อมูลนำเข้า')),
                ('output_data', models.JSONField(blank=True, null=True, verbose_name='ผลลัพธ์การทำงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาที่บันทึก')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งงาน')),
            ],
            options={
                'verbose_name': 'บันทึกประวัติเพื่อนร่วมงาน AI',
                'verbose_name_plural': 'บันทึกประวัติเพื่อนร่วมงาน AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
