# Generated by Django 6.0.1 on 2026-06-06 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_aicoworkerlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontask',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตรวจสอบ (QA)'),
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'In Progress'), ('reviewing', 'Reviewing'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', max_length=15, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='weeklygoal',
            name='status',
            field=models.CharField(choices=[('todo', 'รอดำเนินการ (To Do)'), ('doing', 'กำลังทำ (In Progress)'), ('reviewing', 'รอตรวจสอบ (Reviewing)'), ('done', 'เสร็จสิ้น (Done)'), ('blocked', 'ติดปัญหา (Blocked)')], default='todo', max_length=15, verbose_name='สถานะ'),
        ),
    ]
