# Generated by Django 6.0.1 on 2026-06-06 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_actiontask_reviewer_alter_actiontask_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontask',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_tasks', to='ops.weeklygoal', verbose_name='เป้าหมาย (Goal)'),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='expected_challenges',
            field=models.TextField(blank=True, verbose_name='อุปสรรคความเสี่ยงที่คาดการณ์'),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='strategy',
            field=models.TextField(blank=True, verbose_name='กลยุทธ์หลัก (Action Plan)'),
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ'),
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='idea',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_task', to='ops.meetingidea', verbose_name='ไอเดียต้นฉบับ'),
        ),
    ]
