# Generated by Django 6.0.1 on 2026-06-06 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_actiontask_goal_weeklygoal_expected_challenges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ชื่อป้ายกำกับ')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='สี (Bootstrap class)')),
            ],
        ),
        migrations.AddField(
            model_name='actiontask',
            name='actual_hours',
            field=models.FloatField(default=0, verbose_name='เวลาที่ใช้จริง (ชั่วโมง)'),
        ),
        migrations.AddField(
            model_name='actiontask',
            name='estimated_hours',
            field=models.FloatField(default=0, verbose_name='เวลาที่คาดหวัง (ชั่วโมง)'),
        ),
        migrations.CreateModel(
            name='ActionTaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่องานย่อย')),
                ('is_completed', models.BooleanField(default=False, verbose_name='เสร็จสิ้นแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='ops.actiontask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ops/tasks/attachments/', verbose_name='ไฟล์แนบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ops.actiontask')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='ความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ops.actiontask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actiontask',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='ops.tasktag', verbose_name='ป้ายกำกับ'),
        ),
    ]
