# Generated by Django 6.0.1 on 2026-07-15 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_tasktag_actiontask_actual_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อขั้นตอน')),
                ('status', models.CharField(choices=[('todo', 'รอดำเนินการ (To Do)'), ('doing', 'กำลังทำ (In Progress)'), ('done', 'เสร็จสิ้น (Done)'), ('blocked', 'ติดปัญหา (Blocked)')], default='todo', max_length=15, verbose_name='สถานะ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดขั้นตอน')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_steps', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับผิดชอบ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ops.actiontask')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
