# Generated by Django 5.2.7 on 2026-02-28 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ฐานเงินเดือน')),
                ('social_security_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='อัตราประกันสังคม (%)')),
                ('social_security_cap', models.DecimalField(decimal_places=2, default=750, max_digits=10, verbose_name='เพดานประกันสังคม (บาท)')),
                ('tax_withholding', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='หักภาษี ณ ที่จ่าย (บาท)')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='เลขบัญชีธนาคาร')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='ชื่อธนาคาร')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'การตั้งค่าเงินเดือนพนักงาน',
                'verbose_name_plural': 'การตั้งค่าเงินเดือนพนักงาน',
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=2)),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('working_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='วันทำงานจริง (วัน)')),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='OT (ชั่วโมง)')),
                ('team_mgmt_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าบริหารทีม (บาท)')),
                ('professional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าวิชาชีพ (บาท)')),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าคอมมิชชัน (บาท)')),
                ('pb_l_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PB&Livascore')),
                ('absent_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='จำนวนวันที่ขาดงาน (วัน)')),
                ('absent_deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เงินหักจากการขาดงาน (บาท)')),
                ('advance_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินเบิกล่วงหน้า (บาท)')),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินออมสะสม (บาท)')),
                ('lost_equipment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าของหาย (บาท)')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายการหักอื่นๆ (บาท)')),
                ('status', models.CharField(choices=[('DRAFT', 'แบบร่าง (Draft)'), ('SUBMITTED', 'รอการตรวจสอบ (Waiting)'), ('APPROVED', 'อนุมัติแล้ว (Approved)'), ('REJECTED', 'ส่งกลับเพื่อแก้ไข (Rejected)')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, verbose_name='หมายเหตุ/เหตุผลประกอบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'รายงานผลงานพนักงาน',
                'verbose_name_plural': 'รายงานผลงานพนักงาน',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ฐานเงินเดือน (ขณะที่อนุมัติ)')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='รายได้รวม')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='รายการหักรวม')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='รายได้สุทธิ')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='จ่ายเงินแล้ว')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_record', to='payroll.workreport')),
            ],
            options={
                'verbose_name': 'บันทึกการจ่ายเงินเดือน',
                'verbose_name_plural': 'บันทึกการจ่ายเงินเดือน',
            },
        ),
    ]
