# Generated by Django 5.2.7 on 2026-02-28 07:37

import django.db.models.deletion
import payroll.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalaryconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={},
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='approved_at',
            new_name='processed_at',
        ),
        migrations.RenameField(
            model_name='workreport',
            old_name='pb_l_score',
            new_name='pb_liva_score',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='employeesalaryconfig',
            name='ot_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='อัตรา OT (บาท/ชั่วโมง)'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='ot_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='social_security_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workreport',
            name='admin_remarks',
            field=models.TextField(blank=True, verbose_name='ผู้บริหาร: ข้อเสนอแนะ/เหตุผลที่ตีกลับ'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='incentives',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Incentives (บาท)'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='base_salary_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=payroll.models.get_current_month),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='พนักงาน: หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='year',
            field=models.PositiveSmallIntegerField(default=payroll.models.get_current_year),
        ),
    ]
