# Generated by Django 6.0.1 on 2026-03-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employeesalaryconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryconfig',
            name='is_payroll_member',
            field=models.BooleanField(default=False, help_text='ถ้า False = user นี้ไม่ปรากฏในระบบ Payroll', verbose_name='เป็นพนักงานในระบบ Payroll'),
        ),
    ]
