# Generated by Django 6.0.1 on 2026-03-02 04:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_add_payroll_member_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='เงินเดือนขั้นต่ำ (≥)')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='เงินเดือนสูงสุด (≤, ว่าง = ไม่จำกัด)')),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='อัตรา %')),
                ('salary_cap', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='เพดานฐานคำนวณ (บาท, 0 = ไม่มี)')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
            ],
            options={
                'verbose_name': 'อัตราประกันสังคม (ขั้นบันได)',
                'verbose_name_plural': 'อัตราประกันสังคม (ขั้นบันได)',
                'ordering': ['min_salary'],
            },
        ),
        migrations.AddField(
            model_name='employeesalaryconfig',
            name='employee_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='รหัสพนักงาน (7 หลัก)'),
        ),
        migrations.AddField(
            model_name='employeesalaryconfig',
            name='national_id',
            field=models.CharField(blank=True, max_length=13, verbose_name='เลขบัตรประชาชน'),
        ),
        migrations.AddField(
            model_name='employeesalaryconfig',
            name='use_sso_bracket',
            field=models.BooleanField(default=True, help_text='ถ้าปิด จะใช้อัตราที่กำหนดเฉพาะคนนี้', verbose_name='ใช้อัตราประกันสังคมแบบขั้นบันได'),
        ),
        migrations.AlterField(
            model_name='employeesalaryconfig',
            name='social_security_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('750'), max_digits=10, verbose_name='เพดานประกันสังคมเฉพาะคน (บาท)'),
        ),
        migrations.AlterField(
            model_name='employeesalaryconfig',
            name='social_security_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='อัตราประกันสังคมเฉพาะคน (%)'),
        ),
    ]
