# Generated by Django 5.2.7 on 2026-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('analysis_data', models.TextField(help_text='JSON or Markdown from AI')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='e.g. AAPL, BTC-USD, PTT.BK, GC=F', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('STOCK', 'Stock (หุ้น)'), ('CRYPTO', 'Cryptocurrency'), ('COMMODITY', 'Commodity (ทอง/น้ำมัน)'), ('FOREX', 'Forex')], default='STOCK', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'ordering': ['symbol'],
            },
        ),
    ]
