# Generated by Django 6.0.1 on 2026-02-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('entry_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('category', models.CharField(choices=[('STOCK', 'Stock (หุ้น)'), ('CRYPTO', 'Cryptocurrency'), ('COMMODITY', 'Commodity (ทอง/น้ำมัน)'), ('FOREX', 'Forex')], default='STOCK', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['symbol'],
            },
        ),
    ]
