# Generated by Django 5.2.7 on 2026-02-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentumCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('rsi', models.FloatField(default=0.0)),
                ('adx', models.FloatField(default=0.0)),
                ('mfi', models.FloatField(default=0.0)),
                ('rvol', models.FloatField(default=1.0)),
                ('eps_growth', models.FloatField(default=0.0)),
                ('rev_growth', models.FloatField(default=0.0)),
                ('technical_score', models.IntegerField(default=0)),
                ('year_high', models.FloatField(default=0.0)),
                ('upside_to_high', models.FloatField(default=0.0)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-technical_score'],
            },
        ),
    ]
