# Generated by Django 5.2.7 on 2026-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_momentumcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentumcandidate',
            name='symbol_bk',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
