# Generated by Django 5.2.7 on 2026-02-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_scannablesymbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysiscache',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='symbol',
            field=models.CharField(help_text='e.g. AAPL, BTC-USD, PTT.BK, GC=F', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'symbol')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'symbol')},
        ),
    ]
