# Generated by Django 5.2.7 on 2026-03-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_analysiscache_user_momentumcandidate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentumcandidate',
            name='demand_zone_end',
            field=models.FloatField(blank=True, null=True, verbose_name='โซนเข้าซื้อ (ล่าง)'),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='demand_zone_start',
            field=models.FloatField(blank=True, null=True, verbose_name='โซนเข้าซื้อ (บน)'),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='entry_strategy',
            field=models.CharField(blank=True, max_length=100, verbose_name='กลยุทธ์การเข้าซื้อ'),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='risk_reward_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='RR Ratio'),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True, verbose_name='จุดตัดขาดทุน'),
        ),
    ]
