# Generated by Django 5.2.7 on 2026-03-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_momentumcandidate_demand_zone_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentumcandidate',
            name='zone_proximity',
            field=models.FloatField(default=999.0, help_text='Percentage distance to Demand Zone Start'),
        ),
    ]
