# Generated by Django 5.2.7 on 2026-03-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_momentumcandidate_zone_proximity'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentumcandidate',
            name='supply_zone_end',
            field=models.FloatField(blank=True, null=True, verbose_name='โซนขาย (บน)'),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='supply_zone_start',
            field=models.FloatField(blank=True, null=True, verbose_name='โซนขาย (ล่าง)'),
        ),
    ]
