# Generated by Django 6.0.1 on 2026-03-16 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_momentumcandidate_supply_zone_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiFactorCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('momentum_score', models.IntegerField(default=0)),
                ('volume_score', models.IntegerField(default=0)),
                ('sentiment_score', models.IntegerField(default=0)),
                ('fundamental_score', models.IntegerField(default=0)),
                ('super_score', models.IntegerField(default=0)),
                ('rsi', models.FloatField(default=0.0)),
                ('adx', models.FloatField(default=0.0)),
                ('mfi', models.FloatField(default=0.0)),
                ('rvol', models.FloatField(default=1.0)),
                ('eps_growth', models.FloatField(default=0.0)),
                ('rev_growth', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('sentiment_reason', models.TextField(blank=True)),
                ('above_ema200', models.BooleanField(default=False)),
                ('above_ema50', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-super_score'],
            },
        ),
    ]
