# Generated by Django 5.2.7 on 2026-03-17 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_multifactorcandidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('buy_price', models.DecimalField(decimal_places=4, help_text='ราคาทุนเฉลี่ยขณะที่ซื้อ', max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=4, help_text='ราคาที่ขายออกไป', max_digits=12)),
                ('profit_loss', models.DecimalField(decimal_places=4, help_text='กำไร/ขาดทุนสุทธิ (เป็นจำนวนเงิน)', max_digits=12)),
                ('profit_loss_pct', models.DecimalField(decimal_places=2, help_text='กำไร/ขาดทุน (%)', max_digits=8)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sold Stock',
                'verbose_name_plural': 'Sold Stocks',
                'ordering': ['-sold_at'],
            },
        ),
    ]
