# Generated by Django 6.0.1 on 2026-03-19 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_soldstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecisionScanCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_run', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('symbol_bk', models.CharField(blank=True, max_length=30)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('rsi', models.FloatField(default=0.0)),
                ('adx', models.FloatField(default=0.0)),
                ('mfi', models.FloatField(default=0.0)),
                ('rvol', models.FloatField(default=1.0)),
                ('eps_growth', models.FloatField(default=0.0)),
                ('rev_growth', models.FloatField(default=0.0)),
                ('technical_score', models.IntegerField(default=0)),
                ('avg_volume_20d', models.FloatField(default=0.0)),
                ('rvol_bullish', models.BooleanField(default=True)),
                ('erc_volume_confirmed', models.BooleanField(default=False)),
                ('zone_target_source', models.CharField(default='52w', max_length=10)),
                ('is_new_entry', models.BooleanField(default=True)),
                ('entry_strategy', models.CharField(blank=True, max_length=100)),
                ('demand_zone_start', models.FloatField(blank=True, null=True)),
                ('demand_zone_end', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('risk_reward_ratio', models.FloatField(blank=True, null=True)),
                ('supply_zone_start', models.FloatField(blank=True, null=True)),
                ('supply_zone_end', models.FloatField(blank=True, null=True)),
                ('year_high', models.FloatField(default=0.0)),
                ('upside_to_high', models.FloatField(default=0.0)),
                ('zone_proximity', models.FloatField(default=999.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_run', '-technical_score'],
            },
        ),
    ]
