# Generated by Django 6.0.1 on 2026-03-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_precisionscancandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='price_pattern',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='price_pattern_score',
            field=models.IntegerField(default=0),
        ),
    ]
