# Generated by Django 6.0.1 on 2026-03-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_add_price_pattern_to_precision_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='rel_momentum_1m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='rel_momentum_3m',
            field=models.FloatField(default=0.0),
        ),
    ]
