# Generated by Django 6.0.1 on 2026-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_add_relative_momentum'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='bb_squeeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ema20_aligned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='macd_crossover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='macd_histogram',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
