# Generated by Django 5.2.7 on 2026-03-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_add_macd_bb_ema20_to_precision_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='rs_rating',
            field=models.IntegerField(default=0),
        ),
    ]
