# Generated by Django 6.0.1 on 2026-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_precisionscancandidate_rs_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ema20_rising',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ema20_slope',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='hh_hl_structure',
            field=models.BooleanField(default=False),
        ),
    ]
