# Generated by Django 6.0.1 on 2026-03-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_tithe_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='market',
            field=models.CharField(db_index=True, default='SET', max_length=10),
        ),
        migrations.AddField(
            model_name='scannablesymbol',
            name='market',
            field=models.CharField(db_index=True, default='SET', max_length=10),
        ),
        migrations.AlterField(
            model_name='scannablesymbol',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='scannablesymbol',
            unique_together={('symbol', 'market')},
        ),
    ]
