# Generated by Django 6.0.1 on 2026-03-30 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_pocket_pivot_vdu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueScanCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_run', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('market_cap', models.FloatField(default=0)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('pb_ratio', models.FloatField(blank=True, null=True)),
                ('peg_ratio', models.FloatField(blank=True, null=True)),
                ('ps_ratio', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(default=0)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('profit_margin', models.FloatField(blank=True, null=True)),
                ('debt_equity', models.FloatField(blank=True, null=True)),
                ('current_ratio', models.FloatField(blank=True, null=True)),
                ('revenue_growth', models.FloatField(blank=True, null=True)),
                ('fcf_yield', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(default=50)),
                ('year_high', models.FloatField(default=0)),
                ('year_low', models.FloatField(default=0)),
                ('pct_from_high', models.FloatField(default=0)),
                ('above_ema200', models.BooleanField(default=False)),
                ('valuation_score', models.IntegerField(default=0)),
                ('quality_score', models.IntegerField(default=0)),
                ('price_action_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('is_new_entry', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_run', '-total_score'],
            },
        ),
    ]
