# Generated by Django 6.0.1 on 2026-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_value_scan_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='cmf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='is_52w_breakout',
            field=models.BooleanField(default=False),
        ),
    ]
