# Generated by Django 5.2.7 on 2026-04-03 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_add_cmf_52w_breakout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='ได้จากการทักหาบอทแล้วดู ID', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='เปิด/ปิด การแจ้งเตือนเข้า Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Profile',
                'verbose_name_plural': 'Telegram Profiles',
            },
        ),
    ]
