# Generated by Django 6.0.1 on 2026-04-03 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_usertelegramprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='is_volume_surge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='volume_surge',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='ScanWatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('alert_threshold', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Watchlist Item',
                'verbose_name_plural': 'Scan Watchlist Items',
                'ordering': ['-added_date'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
