# Generated by Django 6.0.1 on 2026-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_volume_surge_scan_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='atr',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='highest_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='trail_multiplier',
            field=models.FloatField(blank=True, default=2.5),
        ),
    ]
