# Generated by Django 6.0.1 on 2026-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_portfolio_trailing_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannablesymbol',
            name='sector',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
    ]
