# Generated by Django 6.0.1 on 2026-04-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_scannablesymbol_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ichimoku_above_kumo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ichimoku_chikou_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ichimoku_kumo_green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ichimoku_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ichimoku_tk_cross',
            field=models.BooleanField(default=False),
        ),
    ]
