# Generated by Django 6.0.1 on 2026-04-08 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_ichimoku_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='momentumcandidate',
            unique_together={('user', 'symbol')},
        ),
    ]
