# Generated by Django 5.2.7 on 2026-04-09 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_momentum_candidate_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scanwatchlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scanwatchlistitem',
            name='market',
            field=models.CharField(db_index=True, default='SET', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='scanwatchlistitem',
            unique_together={('user', 'symbol', 'market')},
        ),
    ]
