# Generated by Django 6.0.1 on 2026-04-09 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_alter_scanwatchlistitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CupHandleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_run', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('cup_high', models.FloatField(default=0.0)),
                ('cup_low', models.FloatField(default=0.0)),
                ('cup_depth_pct', models.FloatField(default=0.0)),
                ('cup_length_days', models.IntegerField(default=0)),
                ('cup_start_date', models.DateField(blank=True, null=True)),
                ('cup_end_date', models.DateField(blank=True, null=True)),
                ('handle_high', models.FloatField(default=0.0)),
                ('handle_low', models.FloatField(default=0.0)),
                ('handle_depth_pct', models.FloatField(default=0.0)),
                ('handle_length_days', models.IntegerField(default=0)),
                ('handle_start_date', models.DateField(blank=True, null=True)),
                ('breakout_price', models.FloatField(default=0.0)),
                ('target_price', models.FloatField(default=0.0)),
                ('stop_loss', models.FloatField(default=0.0)),
                ('risk_reward', models.FloatField(default=0.0)),
                ('avg_vol_20d', models.FloatField(default=0.0)),
                ('cup_vol_confirmed', models.BooleanField(default=False)),
                ('handle_vol_dry', models.BooleanField(default=False)),
                ('stage', models.CharField(default='forming', max_length=20)),
                ('confidence_score', models.IntegerField(default=0)),
                ('rs_rating', models.IntegerField(default=0)),
                ('adx', models.FloatField(default=0.0)),
                ('rsi', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cup & Handle Candidate',
                'ordering': ['-scan_run', '-confidence_score'],
                'indexes': [models.Index(fields=['user', 'scan_run'], name='stocks_cuph_user_id_4d72be_idx')],
            },
        ),
    ]
