# Generated by Django 5.2.7 on 2026-04-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0031_cup_handle_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='vcp_contractions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='vcp_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='vcp_tightness',
            field=models.FloatField(default=0.0),
        ),
    ]
