# Generated by Django 6.0.1 on 2026-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_precisionscancandidate_vcp_contractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='vcp_vdu',
            field=models.BooleanField(default=False),
        ),
    ]
