# Generated by Django 5.2.7 on 2026-04-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0033_precisionscancandidate_vcp_vdu'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstock',
            name='bought_at',
            field=models.DateTimeField(blank=True, help_text='วันที่เข้าซื้อครั้งแรก', null=True),
        ),
    ]
