# Generated by Django 6.0.1 on 2026-04-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0034_soldstock_bought_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USSepaCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_run', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('stage2', models.BooleanField(default=False)),
                ('rs_rating', models.IntegerField(default=0)),
                ('vcp_setup', models.BooleanField(default=False)),
                ('vcp_contractions', models.IntegerField(default=0)),
                ('vcp_tightness', models.FloatField(default=0.0)),
                ('vcp_vdu', models.BooleanField(default=False)),
                ('pocket_pivot', models.BooleanField(default=False)),
                ('vdu_near_zone', models.BooleanField(default=False)),
                ('adx', models.FloatField(default=0.0)),
                ('rsi', models.FloatField(default=0.0)),
                ('rvol', models.FloatField(default=1.0)),
                ('year_high', models.FloatField(default=0.0)),
                ('upside_to_high', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'US SEPA Candidate',
                'ordering': ['-scan_run', '-rs_rating'],
                'indexes': [models.Index(fields=['user', 'scan_run'], name='stocks_usse_user_id_c0679c_idx')],
            },
        ),
    ]
