# Generated by Django 6.0.1 on 2026-04-14 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0035_us_sepa_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='momentumcandidate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='bb_squeeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='macd_crossover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='market',
            field=models.CharField(db_index=True, default='SET', max_length=10),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='rel_1m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='rel_3m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='rs_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='rvol_bullish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='momentumcandidate',
            name='stage2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='momentumcandidate',
            unique_together={('user', 'symbol', 'market')},
        ),
    ]
