# Generated by Django 6.0.1 on 2026-04-14 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0036_momentum_candidate_us_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MorningBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report_md', models.TextField(help_text='Markdown report from Gemini AI')),
                ('portfolio_count', models.IntegerField(default=0)),
                ('momentum_set_count', models.IntegerField(default=0)),
                ('momentum_us_count', models.IntegerField(default=0)),
                ('precision_count', models.IntegerField(default=0)),
                ('sepa_count', models.IntegerField(default=0)),
                ('cup_handle_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Morning Briefing',
                'ordering': ['-created_at'],
            },
        ),
    ]
