# Generated by Django 6.0.1 on 2026-04-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0037_morning_briefing'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='market',
            field=models.CharField(choices=[('SET', 'หุ้นไทย (SET)'), ('US', 'หุ้น US'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'อื่นๆ')], default='SET', max_length=10),
        ),
        migrations.AddField(
            model_name='soldstock',
            name='market',
            field=models.CharField(choices=[('SET', 'หุ้นไทย (SET)'), ('US', 'หุ้น US'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'อื่นๆ')], default='SET', max_length=10),
        ),
    ]
