# Generated by Django 6.0.1 on 2026-04-16 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0038_add_market_to_portfolio_soldstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cuphandlecandidate',
            name='stocks_cuph_user_id_4d72be_idx',
        ),
        migrations.AddField(
            model_name='cuphandlecandidate',
            name='breakout_vol_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuphandlecandidate',
            name='market',
            field=models.CharField(default='SET', max_length=10),
        ),
        migrations.AddIndex(
            model_name='cuphandlecandidate',
            index=models.Index(fields=['user', 'scan_run', 'market'], name='stocks_cuph_user_id_e0c098_idx'),
        ),
    ]
