# Generated by Django 6.0.1 on 2026-04-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0039_add_market_breakoutvol_to_cuphandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifactorcandidate',
            name='market',
            field=models.CharField(default='SET', max_length=10),
        ),
    ]
