# Generated by Django 5.2.7 on 2026-04-17 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0040_add_market_to_multifactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurtleScanCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_run', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('market', models.CharField(db_index=True, default='SET', max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('sys1_breakout', models.BooleanField(default=False)),
                ('high_20d', models.FloatField(default=0.0)),
                ('low_10d', models.FloatField(default=0.0)),
                ('sys2_breakout', models.BooleanField(default=False)),
                ('high_55d', models.FloatField(default=0.0)),
                ('low_20d', models.FloatField(default=0.0)),
                ('avg_vol_20d', models.FloatField(default=0.0)),
                ('atr_20d', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turtle Scan Candidate',
                'ordering': ['-scan_run', 'symbol'],
            },
        ),
    ]
