# Generated by Django 5.2.7 on 2026-04-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0041_turtlescancandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='strategy',
            field=models.CharField(blank=True, help_text='e.g. Turtle S1, SEPA, Cup&Handle', max_length=50, null=True),
        ),
    ]
