# Generated by Django 5.2.7 on 2026-04-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0042_portfolio_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanwatchlistitem',
            name='strategy',
            field=models.CharField(choices=[('PRECISION', 'Precision (Demand Zone)'), ('TURTLE_S1', 'Turtle S1 (Breakout 20D / Exit 10D Low)'), ('TURTLE_S2', 'Turtle S2 (Breakout 55D / Exit 20D Low)'), ('SEPA', 'SEPA (Minervini)'), ('CUP_HANDLE', 'Cup & Handle'), ('OTHER', 'อื่นๆ')], default='PRECISION', max_length=50),
        ),
    ]
