# Generated by Django 5.2.7 on 2026-04-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0044_create_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannablesymbol',
            name='last_cap_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scannablesymbol',
            name='market_cap',
            field=models.FloatField(default=0.0, help_text='Market capitalization in THB for SET, USD for US'),
        ),
    ]
