# Generated by Django 6.0.1 on 2026-04-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0045_scannablesymbol_last_cap_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlescancandidate',
            name='pct_to_20d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='pct_to_55d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='sys1_days_ago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='sys1_near',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='sys2_days_ago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='sys2_near',
            field=models.BooleanField(default=False),
        ),
    ]
