# Generated by Django 5.2.7 on 2026-04-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0046_turtle_extended_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldstock',
            name='profit_loss_thb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='กำไร/ขาดทุนในหน่วยบาท (คำนวณ ณ วันขาย)', max_digits=14),
        ),
        migrations.AddField(
            model_name='soldstock',
            name='sell_revenue_thb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='รายได้รวมในหน่วยบาท', max_digits=14),
        ),
        migrations.AddField(
            model_name='soldstock',
            name='settlement_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='อัตราแลกเปลี่ยน ณ ตอนขาย (e.g. USDTHB)', max_digits=12),
        ),
    ]
