# Generated by Django 5.2.7 on 2026-04-22 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0047_soldstock_profit_loss_thb_soldstock_sell_revenue_thb_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('META_API', 'MetaApi (MT4/MT5 Cloud)'), ('OANDA', 'OANDA (REST API)'), ('IBKR', 'Interactive Brokers'), ('TOP_TRADER', 'Top-Trader (SET)'), ('OTHER', 'อื่นๆ / Manual')], default='META_API', max_length=20)),
                ('account_id', models.CharField(help_text='เลขพอร์ต หรือ Account ID', max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='API Key / Token', max_length=255)),
                ('api_secret', models.CharField(blank=True, help_text='API Secret / Password', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='เปิด/ปิด การให้ Robot เข้าถึงพอร์ตนี้')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Account',
                'unique_together': {('user', 'account_id', 'broker')},
            },
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='e.g. XAUUSD, GC=F, PTT', max_length=20)),
                ('order_id', models.CharField(blank=True, help_text='Ticket ID จาก Broker', max_length=100)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('volume', models.DecimalField(decimal_places=4, help_text='จำนวน Lots / Units', max_digits=12)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'รอเข้าซื้อ (Pending)'), ('OPEN', 'เปิดสถานะแล้ว (Live)'), ('CLOSED', 'ปิดสถานะแล้ว (Closed)'), ('CANCELLED', 'ยกเลิก (Cancelled)')], default='PENDING', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='กำไร/ขาดทุนสุทธิ (Net P/L)', max_digits=14)),
                ('strategy', models.CharField(blank=True, help_text='e.g. Turtle S1, Precision DZ', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='บันทึกเพิ่มเติมจาก Robot หรือ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stocks.tradingaccount')),
            ],
            options={
                'verbose_name': 'Trade Order',
                'ordering': ['-opened_at', '-created_at'],
            },
        ),
    ]
