# Generated by Django 5.2.7 on 2026-04-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0048_tradingaccount_tradeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='is_explosive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='launcher_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='tightness_idx',
            field=models.FloatField(default=99.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='turtle_dist_pct',
            field=models.FloatField(default=99.0),
        ),
    ]
