# Generated by Django 5.2.7 on 2026-04-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0049_precisionscancandidate_is_explosive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key / Token', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='api_secret',
            field=models.CharField(blank=True, help_text='API Secret / Password', max_length=1000),
        ),
    ]
