# Generated by Django 5.2.7 on 2026-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0050_alter_tradingaccount_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='Gold Robot', max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, help_text='บันทึกกิจกรรมล่าสุดของบอท')),
            ],
            options={
                'verbose_name': 'Bot Activity',
                'verbose_name_plural': 'Bot Activities',
            },
        ),
    ]
