# Generated by Django 5.2.7 on 2026-04-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0051_botactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='api_key',
            field=models.TextField(blank=True, help_text='API Key / Token'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='api_secret',
            field=models.TextField(blank=True, help_text='API Secret / Password'),
        ),
    ]
