# Generated by Django 5.2.7 on 2026-04-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0052_alter_tradingaccount_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlescancandidate',
            name='adx',
            field=models.FloatField(blank=True, help_text='Average Directional Index', null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='is_elite',
            field=models.BooleanField(default=False, help_text='ผ่านเกณฑ์คุณภาพระดับสูงครบทุกข้อ'),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='rs_rating',
            field=models.IntegerField(blank=True, help_text='Relative Strength Rating', null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='stage2',
            field=models.BooleanField(default=False, help_text='True if Price > SMA150 and SMA150 rising'),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='technical_score',
            field=models.IntegerField(blank=True, help_text='คะแนนจาก Precision Scan', null=True),
        ),
    ]
