# Generated by Django 5.2.7 on 2026-04-28 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0053_turtlescancandidate_adx_turtlescancandidate_is_elite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDashboardInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('set_top_stocks', models.JSONField(default=list, help_text='Top 5 SET stocks metadata')),
                ('us_top_stocks', models.JSONField(default=list, help_text='Top 5 US stocks metadata')),
                ('ai_strategy', models.TextField(help_text='AI Analysis and Strategy Summary')),
                ('market_outlook', models.CharField(blank=True, help_text='e.g. Bullish, Sideways, Caution', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Dashboard Insight',
                'verbose_name_plural': 'Investment Dashboard Insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
