# Generated by Django 5.2.7 on 2026-05-11 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0054_investmentdashboardinsight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_enabled', models.BooleanField(default=False)),
                ('alert_high_target', models.FloatField(blank=True, null=True)),
                ('alert_low_target', models.FloatField(blank=True, null=True)),
                ('default_capital', models.FloatField(default=1000.0)),
                ('default_risk_pct', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
