# Generated by Django 6.0.1 on 2026-05-12 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0055_usertradingconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeorder',
            name='actual_rr',
            field=models.DecimalField(decimal_places=3, default=0, help_text='R:R จริงที่ได้รับ', max_digits=8),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=0, help_text='ค่านายหน้า Broker', max_digits=10),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='duration_sec',
            field=models.IntegerField(default=0, help_text='ระยะเวลา Hold (วินาที)'),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='exit_reason',
            field=models.CharField(blank=True, help_text='TP / SL / Manual / Panic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='gross_pl',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gross P/L ก่อนหักค่าธรรมเนียม', max_digits=14),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='pips',
            field=models.DecimalField(decimal_places=2, default=0, help_text='จำนวน Pips/Points ที่ได้/เสีย', max_digits=10),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='risk_pct',
            field=models.DecimalField(decimal_places=3, default=0, help_text='ความเสี่ยงเป็น % ของบัญชี', max_digits=6),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='risk_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ความเสี่ยงเป็น USD ($)', max_digits=12),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='signal_source',
            field=models.CharField(blank=True, help_text='สัญญาณที่ trigger: DC10, DC20, DC55, Manual', max_length=100),
        ),
        migrations.AddField(
            model_name='tradeorder',
            name='swap',
            field=models.DecimalField(decimal_places=4, default=0, help_text='ค่า Swap / ดอกเบี้ยค้างคืน', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net P/L หลังหักค่าธรรมเนียม', max_digits=14),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='strategy',
            field=models.CharField(blank=True, help_text='e.g. SNIPER, TURTLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='symbol',
            field=models.CharField(help_text='e.g. XAUUSD, GC=F', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='volume',
            field=models.DecimalField(decimal_places=4, help_text='Lots', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['user', 'symbol', 'status'], name='stocks_trad_user_id_ef96f5_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeorder',
            index=models.Index(fields=['user', 'opened_at'], name='stocks_trad_user_id_e6271e_idx'),
        ),
    ]
