# Generated by Django 5.2.7 on 2026-05-15 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0056_tradeorder_full_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('STOCK', 'Stock (หุ้น)'), ('CRYPTO', 'Cryptocurrency'), ('COMMODITY', 'Commodity (ทอง/น้ำมัน)'), ('FOREX', 'Forex'), ('CASH', 'Cash (เงินสด)')], default='STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='market',
            field=models.CharField(choices=[('SET', 'หุ้นไทย (SET)'), ('US', 'หุ้น US'), ('CRYPTO', 'Cryptocurrency'), ('CASH', 'เงินสด (Cash)'), ('OTHER', 'อื่นๆ')], default='SET', max_length=10),
        ),
        migrations.AlterField(
            model_name='soldstock',
            name='market',
            field=models.CharField(choices=[('SET', 'หุ้นไทย (SET)'), ('US', 'หุ้น US'), ('CRYPTO', 'Cryptocurrency'), ('CASH', 'เงินสด (Cash)'), ('OTHER', 'อื่นๆ')], default='SET', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeorder',
            name='pips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='category',
            field=models.CharField(choices=[('STOCK', 'Stock (หุ้น)'), ('CRYPTO', 'Cryptocurrency'), ('COMMODITY', 'Commodity (ทอง/น้ำมัน)'), ('FOREX', 'Forex'), ('CASH', 'Cash (เงินสด)')], default='STOCK', max_length=20),
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='ยอดเงิน (บวก=เข้า, ลบ=ออก)', max_digits=16)),
                ('currency', models.CharField(default='THB', max_length=10)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'เงินเข้า (Deposit)'), ('WITHDRAWAL', 'เงินออก (Withdrawal)'), ('DIVIDEND', 'ปันผล (Dividend)'), ('FEE', 'ค่าธรรมเนียม/อื่นๆ (Fee)'), ('BUY', 'ซื้อหุ้น (Buy)'), ('SELL', 'ขายหุ้น (Sell)')], default='DEPOSIT', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Transaction',
                'verbose_name_plural': 'Cash Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='THB', help_text='e.g. THB, USD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_cash', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Cash',
                'verbose_name_plural': 'Portfolio Cash',
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
