# Generated by Django 5.2.7 on 2026-05-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0057_alter_portfolio_category_alter_portfolio_market_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'เงินเข้า (Deposit)'), ('WITHDRAWAL', 'เงินออก (Withdrawal)'), ('DIVIDEND', 'ปันผล (Dividend)'), ('FEE', 'ค่าธรรมเนียม/อื่นๆ (Fee)'), ('BUY', 'ซื้อหุ้น (Buy)'), ('SELL', 'ขายหุ้น (Sell)'), ('ADJUSTMENT', 'ปรับปรุงยอด (Adjustment)')], default='DEPOSIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('STOCK', 'Stock (หุ้น)'), ('CRYPTO', 'Cryptocurrency'), ('COMMODITY', 'Commodity (ทอง/น้ำมัน)'), ('FOREX', 'Forex'), ('FUND', 'Mutual Fund (กองทุน)'), ('CASH', 'Cash (เงินสด)')], default='STOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='market',
            field=models.CharField(choices=[('SET', 'หุ้นไทย (SET)'), ('US', 'หุ้น US'), ('CRYPTO', 'Cryptocurrency'), ('FUND', 'กองทุน (Fund)'), ('CASH', 'เงินสด (Cash)'), ('OTHER', 'อื่นๆ')], default='SET', max_length=10),
        ),
        migrations.AlterField(
            model_name='soldstock',
            name='market',
            field=models.CharField(choices=[('SET', 'หุ้นไทย (SET)'), ('US', 'หุ้น US'), ('CRYPTO', 'Cryptocurrency'), ('FUND', 'กองทุน (Fund)'), ('CASH', 'เงินสด (Cash)'), ('OTHER', 'อื่นๆ')], default='SET', max_length=10),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='category',
            field=models.CharField(choices=[('STOCK', 'Stock (หุ้น)'), ('CRYPTO', 'Cryptocurrency'), ('COMMODITY', 'Commodity (ทอง/น้ำมัน)'), ('FOREX', 'Forex'), ('FUND', 'Mutual Fund (กองทุน)'), ('CASH', 'Cash (เงินสด)')], default='STOCK', max_length=20),
        ),
        migrations.CreateModel(
            name='PortfolioFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อกองทุน')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='ต้นทุน (Cost)')),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='มูลค่าตลาด (Market Value)')),
                ('currency', models.CharField(default='THB', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Fund',
                'verbose_name_plural': 'Portfolio Funds',
            },
        ),
    ]
