# Generated by Django 6.0.1 on 2026-05-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0058_alter_cashtransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='entry_price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=15),
        ),
    ]
