# Generated by Django 6.0.1 on 2026-05-18 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0059_crypto_decimal_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeanReversionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_run', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('market', models.CharField(db_index=True, default='SET', max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('direction', models.CharField(choices=[('oversold', 'Oversold'), ('overbought', 'Overbought')], default='oversold', max_length=10)),
                ('rsi', models.FloatField(default=50.0)),
                ('adx', models.FloatField(default=0.0)),
                ('avg_vol_20d', models.FloatField(default=0.0)),
                ('rvol', models.FloatField(default=1.0)),
                ('pattern', models.CharField(blank=True, default='', max_length=30)),
                ('support_level', models.FloatField(blank=True, null=True)),
                ('resistance_level', models.FloatField(blank=True, null=True)),
                ('mean_target', models.FloatField(blank=True, null=True)),
                ('dist_to_support_pct', models.FloatField(default=0.0)),
                ('dist_to_resistance_pct', models.FloatField(default=0.0)),
                ('upside_pct', models.FloatField(default=0.0)),
                ('r_score', models.IntegerField(default=0)),
                ('rs_rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mean Reversion Candidate',
                'ordering': ['-scan_run', '-r_score'],
            },
        ),
    ]
