# Generated by Django 5.2.7 on 2026-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0060_mean_reversion_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ehlers_fisher',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ehlers_fisher_trigger',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ehlers_laguerre_rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ehlers_supersmoother',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
