# Generated by Django 5.2.7 on 2026-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0061_precisionscancandidate_ehlers_fisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ehlers_itl_bullish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ehlers_itl_daily',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ehlers_itl_weekly',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
