# Generated by Django 6.0.1 on 2026-05-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0062_precisionscancandidate_ehlers_itl_bullish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussepacandidate',
            name='earnings_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ussepacandidate',
            name='eps_accel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ussepacandidate',
            name='eps_growth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ussepacandidate',
            name='rev_growth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ussepacandidate',
            name='roe',
            field=models.FloatField(default=0.0),
        ),
    ]
