# Generated by Django 6.0.1 on 2026-05-29 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0063_sepa_earnings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIManualScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=5)),
                ('reasoning', models.TextField()),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Manual Scan Result',
                'verbose_name_plural': 'AI Manual Scan Results',
                'ordering': ['rank', 'grade', 'symbol'],
            },
        ),
    ]
