# Generated by Django 5.2.7 on 2026-06-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0064_aimanualscanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimanualscanresult',
            name='scan_run',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
