# Generated by Django 5.2.7 on 2026-06-13 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0065_aimanualscanresult_scan_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAgentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report_date', models.DateField(db_index=True)),
                ('time_slot', models.CharField(max_length=10)),
                ('report_md', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_agent_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Agent Report',
                'verbose_name_plural': 'Daily Agent Reports',
                'ordering': ['-report_date', '-time_slot'],
                'unique_together': {('user', 'report_date', 'time_slot')},
            },
        ),
    ]
