# Generated by Django 5.2.7 on 2026-07-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0067_precisionscancandidate_prebreakout_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
