# Generated by Django 5.2.7 on 2026-07-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0068_cashtransaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ma10',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ma50',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='pp_at_ma50',
            field=models.BooleanField(default=False),
        ),
    ]
