# Generated by Django 5.2.7 on 2026-07-17 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0069_precision_pp_ma50'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('check_interval_minutes', models.PositiveIntegerField(default=30)),
                ('alert_stop_loss', models.BooleanField(default=True, verbose_name='แจ้งเตือน Stop Loss')),
                ('alert_take_profit', models.BooleanField(default=True, verbose_name='แจ้งเตือน Take Profit')),
                ('alert_breakout_add', models.BooleanField(default=True, verbose_name='แจ้งเตือน Breakout (ซื้อเพิ่ม)')),
                ('alert_watchlist_entry', models.BooleanField(default=False, verbose_name='แจ้งเตือนโซนเข้าซื้อ (Watchlist)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alert_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Alert Config',
                'verbose_name_plural': 'Stock Alert Configs',
            },
        ),
        migrations.CreateModel(
            name='StockAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('alert_type', models.CharField(choices=[('SL', 'Stop Loss'), ('TP', 'Take Profit'), ('BREAKOUT', 'Breakout (ซื้อเพิ่ม)'), ('WATCHLIST_ENTRY', 'โซนเข้าซื้อ (Watchlist)')], max_length=20)),
                ('strategy', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('price', models.FloatField()),
                ('reference_level', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alert_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Alert Event',
                'verbose_name_plural': 'Stock Alert Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
