# Generated by Django 5.2.7 on 2026-08-01 09:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0070_stockalertconfig_stockalertevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='ชื่อหุ้น')),
                ('market', models.CharField(default='SET', max_length=10)),
                ('dividend_date', models.DateField(verbose_name='วันที่ได้รับปันผล')),
                ('dividend_per_share', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='ปันผลต่อหุ้น')),
                ('shares', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='จำนวนหุ้น')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='อัตราภาษีหัก ณ ที่จ่าย (%)')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dividend Record',
                'verbose_name_plural': 'Dividend Records',
                'ordering': ['-dividend_date', '-created_at'],
            },
        ),
    ]
