# Generated by Django 5.2.7 on 2026-08-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0071_dividendrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tp1_hit',
            field=models.BooleanField(blank=True, default=False, verbose_name='ล็อกกำไรบางส่วนแล้ว (TP1)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tp1_price',
            field=models.FloatField(blank=True, null=True, verbose_name='ราคา ณ TP1'),
        ),
        migrations.AlterField(
            model_name='stockalertevent',
            name='alert_type',
            field=models.CharField(choices=[('SL', 'Stop Loss'), ('TP', 'Take Profit'), ('BREAKOUT', 'Breakout (ซื้อเพิ่ม)'), ('WATCHLIST_ENTRY', 'โซนเข้าซื้อ (Watchlist)'), ('TP_PARTIAL', 'ล็อกกำไรบางส่วน (Let Profit Run)'), ('TRAILING_EXIT', 'หลุด Trailing Stop (ขายส่วนที่เหลือ)')], max_length=20),
        ),
    ]
