# Generated by Django 5.2.7 on 2026-08-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0072_portfolio_tp1_hit_portfolio_tp1_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='alerted_in_zone',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
