# Generated by Django 5.2.7 on 2026-08-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0073_watchlist_alerted_in_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='alerted_in_zone',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='last_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
