# Generated by Django 5.2.7 on 2026-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0074_remove_watchlist_alerted_in_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalertconfig',
            name='alert_retention_days',
            field=models.PositiveIntegerField(default=30, verbose_name='เก็บประวัติแจ้งเตือนกี่วัน'),
        ),
    ]
