# Generated by Django 5.2.7 on 2026-08-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0075_stockalertconfig_alert_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalertevent',
            name='market',
            field=models.CharField(choices=[('SET', 'หุ้นไทย (SET)'), ('US', 'หุ้น US'), ('CRYPTO', 'Cryptocurrency'), ('FUND', 'กองทุน (Fund)'), ('CASH', 'เงินสด (Cash)'), ('OTHER', 'อื่นๆ')], default='SET', max_length=10),
        ),
    ]
