# Generated by Django 5.2.7 on 2026-08-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0076_stockalertevent_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalertconfig',
            name='alert_reallocate',
            field=models.BooleanField(default=False, verbose_name='แจ้งเตือนสับเปลี่ยนหุ้นในพอร์ต'),
        ),
        migrations.AlterField(
            model_name='stockalertevent',
            name='alert_type',
            field=models.CharField(choices=[('SL', 'Stop Loss'), ('TP', 'Take Profit'), ('BREAKOUT', 'Breakout (ซื้อเพิ่ม)'), ('WATCHLIST_ENTRY', 'โซนเข้าซื้อ (Watchlist)'), ('TP_PARTIAL', 'ล็อกกำไรบางส่วน (Let Profit Run)'), ('TRAILING_EXIT', 'หลุด Trailing Stop (ขายส่วนที่เหลือ)'), ('REALLOCATE', 'แนะนำสับเปลี่ยนหุ้นในพอร์ต')], max_length=20),
        ),
    ]
