# Generated by Django 5.2.7 on 2026-08-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0077_stockalertconfig_alert_reallocate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalertconfig',
            name='alert_distribution_warning',
            field=models.BooleanField(default=True, verbose_name='แจ้งเตือนสัญญาณกระจายขาย/กลับตัว (ก่อนหลุด SL)'),
        ),
        migrations.AlterField(
            model_name='stockalertevent',
            name='alert_type',
            field=models.CharField(choices=[('SL', 'Stop Loss'), ('TP', 'Take Profit'), ('BREAKOUT', 'Breakout (ซื้อเพิ่ม)'), ('WATCHLIST_ENTRY', 'โซนเข้าซื้อ (Watchlist)'), ('TP_PARTIAL', 'ล็อกกำไรบางส่วน (Let Profit Run)'), ('TRAILING_EXIT', 'หลุด Trailing Stop (ขายส่วนที่เหลือ)'), ('REALLOCATE', 'แนะนำสับเปลี่ยนหุ้นในพอร์ต'), ('DISTRIBUTION_WARNING', 'สัญญาณกระจายขาย/กลับตัว')], max_length=20),
        ),
    ]
