# Generated by Django 5.2.7 on 2026-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0078_stockalertconfig_alert_distribution_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalertconfig',
            name='alert_vdu_watch',
            field=models.BooleanField(default=False, verbose_name='แจ้งเตือน Volume Dry-Up (จับตาก่อนเบรก)'),
        ),
        migrations.AlterField(
            model_name='stockalertevent',
            name='alert_type',
            field=models.CharField(choices=[('SL', 'Stop Loss'), ('TP', 'Take Profit'), ('BREAKOUT', 'Breakout (ซื้อเพิ่ม)'), ('WATCHLIST_ENTRY', 'โซนเข้าซื้อ (Watchlist)'), ('TP_PARTIAL', 'ล็อกกำไรบางส่วน (Let Profit Run)'), ('TRAILING_EXIT', 'หลุด Trailing Stop (ขายส่วนที่เหลือ)'), ('REALLOCATE', 'แนะนำสับเปลี่ยนหุ้นในพอร์ต'), ('DISTRIBUTION_WARNING', 'สัญญาณกระจายขาย/กลับตัว'), ('VDU_WATCH', 'จับตาใกล้ชิด (Volume Dry-Up)')], max_length=20),
        ),
    ]
