# Generated by Django 5.2.7 on 2026-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0080_precisionscancandidate_wyckoff_effort_result_warning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='cheat_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='sector_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='sector_strength_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='trend_template_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='trend_template_score',
            field=models.IntegerField(default=0),
        ),
    ]
