# Generated by Django 5.2.7 on 2026-08-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0081_precisionscancandidate_cheat_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='wyckoff_selling_climax',
            field=models.BooleanField(default=False),
        ),
    ]
