# Generated by Django 5.2.7 on 2026-08-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0082_precisionscancandidate_wyckoff_selling_climax'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='wyckoff_upthrust',
            field=models.BooleanField(default=False),
        ),
    ]
