# Generated by Django 6.0.1 on 2026-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0083_precisionscancandidate_wyckoff_upthrust'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='vp_poc_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='vp_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
