# Generated by Django 5.2.7 on 2026-09-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0084_precisionscancandidate_vp_poc_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='adr_20d_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ep_gap_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='episodic_pivot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='htf_base_depth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='htf_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='htf_surge_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ma50_dist_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ttm_squeeze_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='ttm_squeeze_state',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
