# Generated by Django 5.2.7 on 2026-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0085_precisionscancandidate_adr_20d_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussepacandidate',
            name='ma10',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ussepacandidate',
            name='ma50',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ussepacandidate',
            name='pp_at_ma50',
            field=models.BooleanField(default=False),
        ),
    ]
