# Generated by Django 5.2.7 on 2026-09-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0086_ussepacandidate_ma10_ussepacandidate_ma50_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockalertevent',
            name='alert_type',
            field=models.CharField(choices=[('SL', 'Stop Loss'), ('TP', 'Take Profit'), ('BREAKOUT', 'Breakout (ซื้อเพิ่ม)'), ('WATCHLIST_ENTRY', 'โซนเข้าซื้อ (Watchlist)'), ('TP_PARTIAL', 'ล็อกกำไรบางส่วน (Let Profit Run)'), ('TRAILING_EXIT', 'หลุด Trailing Stop (ขายส่วนที่เหลือ)'), ('REALLOCATE', 'แนะนำสับเปลี่ยนหุ้นในพอร์ต'), ('DISTRIBUTION_WARNING', 'สัญญาณกระจายขาย/กลับตัว'), ('VDU_WATCH', 'จับตาใกล้ชิด (Volume Dry-Up)'), ('EXIT_ACTION', 'คำแนะนำออก/ลดพอร์ต (ตรงกับหน้า Exit Plan)')], max_length=20),
        ),
    ]
