# Generated by Django 5.2.7 on 2026-09-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0087_alter_stockalertevent_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='precisionscancandidate',
            name='anti_avg_down_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='atr14',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='atr_stop_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='bl_rr_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='pyramiding_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='risk_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='precisionscancandidate',
            name='risk_per_share',
            field=models.FloatField(default=0.0),
        ),
    ]
