# Generated by Django 5.2.7 on 2026-09-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0088_precisionscancandidate_anti_avg_down_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalertconfig',
            name='alert_market_timing',
            field=models.BooleanField(default=True, verbose_name='แจ้งเตือนภาวะตลาดรวม (Market Timing)'),
        ),
        migrations.AddField(
            model_name='stockalertconfig',
            name='alert_sector_rotation',
            field=models.BooleanField(default=False, verbose_name='แจ้งเตือนการหมุนกลุ่มอุตสาหกรรม (Sector Rotation)'),
        ),
        migrations.AlterField(
            model_name='stockalertevent',
            name='alert_type',
            field=models.CharField(choices=[('SL', 'Stop Loss'), ('TP', 'Take Profit'), ('BREAKOUT', 'Breakout (ซื้อเพิ่ม)'), ('WATCHLIST_ENTRY', 'โซนเข้าซื้อ (Watchlist)'), ('TP_PARTIAL', 'ล็อกกำไรบางส่วน (Let Profit Run)'), ('TRAILING_EXIT', 'หลุด Trailing Stop (ขายส่วนที่เหลือ)'), ('REALLOCATE', 'แนะนำสับเปลี่ยนหุ้นในพอร์ต'), ('DISTRIBUTION_WARNING', 'สัญญาณกระจายขาย/กลับตัว'), ('VDU_WATCH', 'จับตาใกล้ชิด (Volume Dry-Up)'), ('EXIT_ACTION', 'คำแนะนำออก/ลดพอร์ต (ตรงกับหน้า Exit Plan)'), ('MARKET_TIMING', 'ภาวะตลาดรวม (Market Timing)'), ('SECTOR_ROTATION', 'การหมุนกลุ่มอุตสาหกรรม (Sector Rotation)')], max_length=20),
        ),
    ]
