# Generated by Django 6.0.1 on 2026-09-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0091_abcd_thin_retracement_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precisionscancandidate',
            name='abcd_is_thin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='precisionscancandidate',
            name='abcd_quality',
            field=models.CharField(blank=True, default='medium', max_length=10),
        ),
    ]
