# Generated by Django 6.0.1 on 2026-09-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0092_alter_precisionscancandidate_abcd_is_thin_and_more'),
        ('stocks', '0092_bo_abcd_convergence_check'),
    ]

    operations = [
    ]
