# Generated by Django 5.2.7 on 2026-09-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0094_valuescancandidate_market"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precisionscancandidate",
            name="abcd_is_thin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="precisionscancandidate",
            name="abcd_quality",
            field=models.CharField(blank=True, default="medium", max_length=10),
        ),
        migrations.AlterField(
            model_name="precisionscancandidate",
            name="convergence_gap_pct",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="precisionscancandidate",
            name="convergence_status",
            field=models.CharField(blank=True, default="none", max_length=10),
        ),
        migrations.AlterField(
            model_name="valuescancandidate",
            name="market",
            field=models.CharField(db_index=True, default="US", max_length=4),
        ),
        migrations.AlterField(
            model_name="valuescancandidate",
            name="roic",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="valuescancandidate",
            name="roic_spread",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="valuescancandidate",
            name="wacc",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
