# Generated by Django 6.0.1 on 2026-09-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0093_merge_20260909_1340'),
        ('stocks', '0095_sync_field_help_text'),
    ]

    operations = [
    ]
