# Generated by Django 6.0.1 on 2026-09-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0096_merge_20260909_1518'),
        ('stocks', '0097_ussepa_trend_template_stage4'),
    ]

    operations = [
    ]
