# Generated by Django 5.2.17 on 2026-09-16 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0098_precisionscanrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market",
                    models.CharField(db_index=True, default="SET", max_length=10),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("scan_date", models.DateField(db_index=True)),
                ("scan_run", models.DateTimeField()),
                ("price_at_scan", models.FloatField()),
                ("stop_loss", models.FloatField(blank=True, null=True)),
                ("target_price", models.FloatField(blank=True, null=True)),
                ("risk_reward_ratio", models.FloatField(blank=True, null=True)),
                (
                    "entry_strategy",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("sector", models.CharField(blank=True, default="", max_length=100)),
                ("technical_score", models.IntegerField(default=0)),
                ("buy_score", models.IntegerField(default=0)),
                ("rs_rating", models.IntegerField(default=0)),
                (
                    "score_bucket",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10
                    ),
                ),
                ("rsi", models.FloatField(default=0.0)),
                ("adx", models.FloatField(default=0.0)),
                ("rvol", models.FloatField(default=1.0)),
                ("cmf", models.FloatField(blank=True, null=True)),
                ("volume_surge", models.FloatField(default=1.0)),
                ("vcp_setup", models.BooleanField(default=False)),
                ("htf_setup", models.BooleanField(default=False)),
                ("pocket_pivot", models.BooleanField(default=False)),
                ("pp_at_ma50", models.BooleanField(default=False)),
                ("episodic_pivot", models.BooleanField(default=False)),
                ("stage2", models.BooleanField(default=False)),
                ("is_explosive", models.BooleanField(default=False)),
                ("is_52w_breakout", models.BooleanField(default=False)),
                ("ema20_aligned", models.BooleanField(default=False)),
                ("wyckoff_spring", models.BooleanField(default=False)),
                ("vdu_near_zone", models.BooleanField(default=False)),
                ("macd_crossover", models.BooleanField(default=False)),
                ("bb_squeeze", models.BooleanField(default=False)),
                ("inside_bar", models.BooleanField(default=False)),
                ("price_d5", models.FloatField(blank=True, null=True)),
                ("price_d10", models.FloatField(blank=True, null=True)),
                ("price_d20", models.FloatField(blank=True, null=True)),
                ("ret_d5", models.FloatField(blank=True, null=True)),
                ("ret_d10", models.FloatField(blank=True, null=True)),
                ("ret_d20", models.FloatField(blank=True, null=True)),
                ("mfe_pct", models.FloatField(blank=True, null=True)),
                ("mae_pct", models.FloatField(blank=True, null=True)),
                ("first_hit", models.CharField(blank=True, default="", max_length=4)),
                ("r_multiple", models.FloatField(blank=True, null=True)),
                ("bars_evaluated", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=10),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_date", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["user", "market", "status"],
                        name="stocks_scan_user_id_3f0d35_idx",
                    ),
                    models.Index(
                        fields=["user", "scan_date"],
                        name="stocks_scan_user_id_6148eb_idx",
                    ),
                ],
                "unique_together": {("user", "market", "symbol", "scan_date")},
            },
        ),
    ]
