# Generated by Django 6.0.1 on 2026-09-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0098_merge_20260910_1428'),
        ('stocks', '0098_precisionscanrun'),
    ]

    operations = [
    ]
