# Generated by Django 5.2.17 on 2026-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0099_scan_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="initial_stop",
            field=models.FloatField(
                blank=True,
                help_text="จุดตัดขาดทุนที่ตั้งไว้ตอนเปิดสถานะ ไม่เปลี่ยนตามราคาที่ไหลลง",
                null=True,
                verbose_name="Stop ตอนเข้าซื้อ",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="locked_stop",
            field=models.FloatField(
                blank=True,
                help_text="ขยับขึ้นตามกำไรได้ แต่ไม่เคยเลื่อนลง",
                null=True,
                verbose_name="Stop ที่ล็อกไว้",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="stop_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
