# Generated by Django 5.2.7 on 2026-09-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0099_merge_0098_merge_20260910_1428_0098_precisionscanrun'),
        ('stocks', '0100_portfolio_locked_stop'),
    ]

    operations = [
    ]
