# Generated by Django 5.2.7 on 2026-09-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0101_merge_20260916_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlescancandidate',
            name='stop_2n',
            field=models.FloatField(blank=True, help_text='Stop ตามกฎ Turtle = entry − 2N', null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='sys1_raw_breakout',
            field=models.BooleanField(default=False, help_text='ทะลุ High 20 วันแล้ว (ยังไม่ผ่านกฎข้ามของ S1)'),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='sys1_skip_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='sys1_skipped',
            field=models.BooleanField(default=False, help_text='ถูกกฎ S1 สั่งข้าม เพราะ breakout ครั้งก่อนเป็นไม้กำไร'),
        ),
    ]
