# Generated by Django 5.2.7 on 2026-09-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0102_turtlescancandidate_stop_2n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlescancandidate',
            name='donchian_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='donchian_pos_pct',
            field=models.FloatField(blank=True, help_text='ราคาอยู่ตรงไหนในกรอบ (0=ก้น, 100=ยอด)', null=True),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='donchian_signal',
            field=models.CharField(blank=True, default='', help_text='LONG / SHORT / HOLD ตามกฎ 4-Week Rule', max_length=8),
        ),
        migrations.AddField(
            model_name='turtlescancandidate',
            name='donchian_upper',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
