# Generated by Django 6.0.1 on 2026-04-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcategory',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='boardcategory',
            name='external_link',
            field=models.URLField(blank=True, help_text='ลิงก์ภายนอก (ไม่บังคับ)', null=True),
        ),
        migrations.AddField(
            model_name='boardcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board/categories/'),
        ),
    ]
