# Generated by Django 6.0.1 on 2026-04-23 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardcategory_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#64748b', max_length=20)),
            ],
            options={
                'verbose_name': 'Tag',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='boardpost',
            name='post_type',
            field=models.CharField(choices=[('general', 'ทั่วไป'), ('wiki', 'Technical Wiki'), ('sop', 'SOP'), ('faq', 'FAQ'), ('lesson', 'Lesson Learned'), ('announcement', 'ประกาศ')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='boardaccess',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='boardcategory',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BoardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='board/attachments/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='board.boardpost')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boardpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='board.boardtag'),
        ),
    ]
